---
title: 高可用 AI优化汇总
---

# 高可用 AI优化汇总

> 基于 0-ALL.md 的 AI 优化版（原文较大）：正文收录重点篇并补充体系化内容；完整原文见 0-ALL.md。

## AI 补充：体系化梳理与易漏考点

> 本节在汇总原文基础上，补充面试追问、对比项与工程落地注意点。

### 知识地图
- 高可用：限流、熔断、降级、超时重试、幂等、容灾多活
- 高性能：缓存、读写分离、分库分表、负载均衡、MQ 削峰

### 常漏追问
1. **重试为什么会雪崩？** 要抖动退避、幂等、熔断、限流联动。
2. **分库分表后如何分页？** 避免深分页；二次查询或业务截断。
3. **幂等怎么做？** Token、唯一索引、状态机、去重表。

### 工程落地检查清单
- [ ] 是否有明确指标（延迟、吞吐、错误率、积压）？
- [ ] 失败是否可重试且幂等？
- [ ] 是否有限流/超时/降级？
- [ ] 是否有日志、链路追踪与告警？
- [ ] 配置变更与回滚是否可操作？


## TOC

1. 2026 最新高可用系统设计面试题总结：SLA、限流熔断、重试幂等与容灾 (`2026 最新高可用系统设计面试题总结-SLA、限流熔断、重试幂等与容灾.md`)
2. 超时和重试机制详解：超时设置、指数退避、随机抖动、重试风暴与幂等 (`超时和重试机制详解-超时设置、指数退避、随机抖动、重试风暴与幂等.md`)
3. 服务降级与熔断详解：Fallback、熔断器状态机与 Sentinel / Hystrix / Resilience4j 选型 (`服务降级与熔断详解-Fallback、熔断器状态机与 Sentinel Hystrix Resilience4j 选型.md`)
4. 服务限流详解：固定窗口、滑动窗口、令牌桶、漏桶与分布式限流 (`服务限流详解-固定窗口、滑动窗口、令牌桶、漏桶与分布式限流.md`)
5. 高可用系统设计面试题总结：限流、熔断、重试、幂等、容灾与压测 (`高可用系统设计面试题总结-限流、熔断、重试、幂等、容灾与压测.md`)
6. 高可用系统设计详解：SLA、限流熔断、降级容灾、缓存与灰度发布 (`高可用系统设计详解-SLA、限流熔断、降级容灾、缓存与灰度发布.md`)
7. 接口幂等性设计详解：幂等键、Token、唯一索引、去重表与支付回调 (`接口幂等性设计详解-幂等键、Token、唯一索引、去重表与支付回调.md`)
8. 冗余设计详解：RTO/RPO、高可用集群、同城灾备与异地多活 (`冗余设计详解-RTORPO、高可用集群、同城灾备与异地多活.md`)
9. 性能测试和压力测试入门：RPS、QPS、TPS、P99 与压测工具 (`性能测试和压力测试入门-RPS、QPS、TPS、P99 与压测工具.md`)

---

<!-- source: 2026 最新高可用系统设计面试题总结-SLA、限流熔断、重试幂等与容灾.md -->

## [1] 2026 最新高可用系统设计面试题总结：SLA、限流熔断、重试幂等与容灾

---
title: 2026 最新高可用系统设计面试题总结：SLA、限流熔断、重试幂等与容灾
category: 高可用
description: 2026 最新高可用系统设计面试题总结，覆盖 SLA、可用性指标、单点故障、RTO/RPO、限流降级熔断、超时重试、接口幂等、性能压测、故障演练和容灾架构等高频考点。
tag:
  - 高可用
  - 面试题
  - 系统设计
head:
  - - meta
    - name: keywords
      content: 高可用面试题,高可用系统设计面试题,2026 高可用面试题,SLA 面试题,单点故障,限流面试题,降级面试题,熔断面试题,超时重试面试题,接口幂等面试题,RTO,RPO,性能压测,故障演练
---

这部分内容摘自 [JavaGuide](https://javaguide.cn/) 下面几篇文章的重点：

高可用设计：

- [高可用系统设计指南](https://javaguide.cn/高可用/high-availability-system-design.html)
- [冗余设计详解](https://javaguide.cn/高可用/redundancy.html)
- [性能测试入门](https://javaguide.cn/高可用/performance-test.html)

限流、降级、熔断：

- [服务限流详解](https://javaguide.cn/高可用/limit-request.html)
- [降级&熔断详解](https://javaguide.cn/高可用/fallback-and-circuit-breaker.html)

超时、重试、幂等：

- [超时&重试详解](https://javaguide.cn/高可用/timeout-and-retry.html)
- [接口幂等方案总结](https://javaguide.cn/高可用/idempotency.html)

## 高可用基础

### ⭐️什么是高可用？

高可用（High Availability）指系统在面对机器故障、网络抖动、依赖异常、流量突增等情况时，仍然能够尽可能持续提供服务。

它不是追求系统永远不出故障，而是关注 3 件事：

1. **故障尽量少发生**：通过测试、评审、容量规划、灰度发布降低故障概率。
2. **故障发生后影响尽量小**：通过隔离、限流、降级、熔断控制故障范围。
3. **故障发生后恢复尽量快**：通过监控、告警、预案、自动故障转移缩短恢复时间。

![高可用关注三件事](https://oss.javaguide.cn/github/javaguide/高可用/ha-interview-core-three-things.png)

面试里不要把高可用理解成"多部署几台机器"。多副本只能减少单点故障，但真正的高可用还要覆盖流量控制、依赖保护、数据安全、故障发现和恢复闭环。

### 可用性 99.9%、99.99% 分别意味着什么？

可用性通常用一段时间内系统可正常服务的比例衡量。

粗略换算：

| 可用性  | 年不可用时间量级 |
| ------- | ---------------- |
| 99%     | 约 3.65 天       |
| 99.9%   | 约 8.76 小时     |
| 99.99%  | 约 52.56 分钟    |
| 99.999% | 约 5.26 分钟     |

可用性小数点后每多一个 9，背后都意味着更高的架构复杂度、运维成本和故障治理能力。

### 哪些情况会导致系统不可用？

常见原因包括：

- 代码 Bug。
- 服务器宕机。
- 网络故障。
- 数据库、缓存、MQ 等中间件故障。
- 外部依赖接口异常。
- 流量突增导致资源耗尽。
- 慢 SQL、大事务、线程池打满。
- 发布变更引入问题。

高可用设计的关键，是假设这些问题一定会发生，然后提前设计隔离和恢复机制。

### ⭐️提高系统可用性的常见方法有哪些？

常见方法包括：

- 提高代码质量，严格测试和 Code Review。
- 使用集群，减少单点故障。
- 做好限流，避免瞬时流量打垮系统。
- 设置合理超时和重试，避免请求无限堆积。
- 使用熔断机制，防止下游故障拖垮上游。
- 做好服务降级，优先保证核心链路。
- 使用异步调用和消息队列削峰。
- 使用缓存降低核心依赖压力。
- 建立监控、告警、压测和故障演练体系。

![提高系统可用性的三层方法](https://oss.javaguide.cn/github/javaguide/高可用/ha-interview-availability-methods.png)

一个比较完整的回答方式是：先按 **预防、容错、恢复** 三层讲方法，再结合系统实际说明哪些链路是核心链路，哪些功能可以牺牲。

### 什么是单点故障？如何避免？

**单点故障（Single Point of Failure，SPOF）** 指系统中某个组件一旦挂掉，整个系统就不可用。

常见单点和对应方案：

| 单点组件   | 解决方案                       |
| ---------- | ------------------------------ |
| 应用服务器 | 集群部署 + 负载均衡            |
| 数据库     | 主从复制 + 读写分离            |
| 缓存       | Redis Sentinel / Cluster       |
| 消息队列   | 多副本 + 主从切换              |
| 负载均衡   | Keepalived + VIP 漂移 / 多实例 |
| 配置中心   | 集群部署 + 本地缓存兜底        |
| DNS        | 多 DNS 服务商 + 本地 DNS 缓存  |

面试中不要只说"多部署几台"。要强调 **消除单点的前提是流量能自动切换**，光有冗余没有故障检测和切换机制，单点还是单点。

### 灰度发布是什么？为什么重要？

灰度发布（也叫金丝雀发布 / Canary Release）是指新版本不一次性全量推给所有用户，而是先放一小部分流量验证，确认没问题后再逐步扩大范围。

常见策略：

- **按比例放量**：先 1% → 5% → 20% → 50% → 100%。
- **按用户特征放量**：先内部用户 → 活跃用户 → 全量用户。
- **按地域放量**：先非核心地域 → 核心地域。

灰度发布的重要性在于：**把"一次大爆炸"变成"多次小实验"**。即使新版本有 Bug，影响范围也只限于灰度流量，回滚成本低。没有灰度发布，每次上线都是一次全站赌博。

配合灰度发布还要有 **快速回滚能力**。灰度发现问题后，能在秒级或分钟级切回旧版本，而不是等运维手动拉代码重新部署。

## 冗余与容灾

### 什么是冗余？

冗余就是为系统关键组件准备备用能力。当某个节点、机房或链路出现故障时，系统可以切换到备用资源继续服务。

冗余是提升系统可用性的基础手段，但冗余本身不等于高可用。只有配合故障检测、流量切换、数据复制、恢复演练和监控告警，才能真正降低故障影响。

常见冗余对象包括：

- 服务实例冗余。
- 数据库主从或多副本冗余。
- 缓存集群冗余。
- MQ 多副本冗余。
- 机房和地域冗余。

### ⭐️RTO 和 RPO 分别是什么？

RTO 和 RPO 是容灾设计里非常重要的两个指标：

- **RPO（Recovery Point Objective，恢复点目标）**：系统在灾难发生后可接受的数据丢失窗口，也可以理解为恢复时数据最多允许回退到多久之前。RPO 越小，对同步复制、日志复制、跨站点一致性和写入延迟的要求越高。RPO = 0 通常意味着写入必须在多个故障域确认后才能返回，或者有等价的强一致提交机制；代价是写入延迟上升，并且在网络分区时需要在可用性和一致性之间做取舍。
- **RTO（Recovery Time Objective，恢复时间目标）**：可容忍的最大恢复时间，即从故障发生到系统恢复正常服务的时间。RTO=0 表示目标上不允许可感知中断，但在真实系统中更常见的表述是接近 0 或用户无感切换，仍要看故障检测、流量切换和客户端重试行为。

![RTO 与 RPO](https://oss.javaguide.cn/github/javaguide/高可用/redundancy-optimized-rto-rpo-timeline.png)

面试加分点：**RTO/RPO 是目标，不是结果**。声明了某个 RPO/RTO 不等于生产环境一定能做到，必须通过定期演练和压测来验证。不同业务链路可以有不同的 RTO/RPO 要求，不必全站统一。

### 常见冗余架构有哪些？

常见方案包括：

| 方案       | 特点                     | 适用场景                       |
| ---------- | ------------------------ | ------------------------------ |
| 高可用集群 | 多实例部署，故障自动转移 | 大多数在线服务                 |
| 同城灾备   | 同城不同机房之间做备份   | 对延迟敏感，又需要机房容灾     |
| 异地灾备   | 异地准备备份系统         | 容忍一定恢复时间的灾备场景     |
| 同城多活   | 同城多机房同时承接流量   | 可用性要求较高的核心系统       |
| 异地多活   | 多地域同时承接流量       | 金融、支付、大型互联网核心链路 |

从容灾等级来看，可以形成如下连续光谱：

| 容灾等级 | 资源状态                       | 恢复速度 | 成本 |
| -------- | ------------------------------ | -------- | ---- |
| **冷备** | 备用资源未运行，需手动启动     | 小时～天 | 低   |
| **温备** | 部分资源常驻运行，需扩容接管   | 分钟级   | 中   |
| **热备** | 资源和数据持续同步，可快速切换 | 秒～分钟 | 高   |
| **多活** | 多站点同时承载生产流量         | 接近实时 | 很高 |

![容灾架构对比](https://oss.javaguide.cn/github/javaguide/高可用/redundancy-optimized-disaster-recovery-comparison.png)

越靠后的方案越复杂，尤其是异地多活，需要解决数据一致性、流量调度、跨地域延迟、故障切换和回切等问题。并不是所有业务都需要异地多活，强一致写入频繁且跨地域冲突多、无法按用户/地域/租户切分的数据模型、对账补偿能力不足的资金链路等场景要慎重评估。

### 什么是故障转移？

故障转移是指主节点或主链路不可用时，系统自动或手动切换到备用节点继续服务。

故障转移可以是自动的，也可以是自动检测后人工确认。对无状态服务和缓存系统，通常追求自动切换；对数据库主切、跨地域切流、资金链路等高风险场景，很多团队会保留人工确认或审批步骤。

常见例子：

- Redis Sentinel 检测 primary 节点不可用后，选举新的 primary。但需要注意 Redis 复制通常是异步的，故障切换时可能丢失尚未复制到 replica 的数据，**不保证 RPO=0**。
- Nginx + Keepalived 通过 VIP 漂移实现入口高可用。但 Keepalived 不保证已有 TCP 连接无损迁移，切换还受 ARP / 二层网络 / 云厂商 VIP 支持影响。
- 数据库主从切换，让从库提升为主库。

故障转移要特别关注 **误判和脑裂** 问题。检测太敏感可能误切，检测太迟又会延长故障时间。脑裂通常来自网络分区，两个节点都认为自己是主节点。常见防护手段包括多数派投票（如 Redis Sentinel 的 quorum）、仲裁节点、租约机制和 fencing。

对于有状态系统，还需要 **fencing 机制**（如 fencing token、STONITH、写入令牌），确保旧主在失联或恢复后不能继续对共享资源写入，避免双主写入。

Redis Sentinel 相关的面试加分点：quorum 只表示多少 Sentinel 同意 primary 客观下线；实际发起 failover 还涉及 Sentinel 多数派和 leader 选举，因此不要把 quorum 简单理解成 Sentinel 总数的一半。

![故障转移流程](https://oss.javaguide.cn/github/javaguide/高可用/redundancy-optimized-failover-process.png)

## 限流

### ⭐️为什么要做限流？

限流是为了控制进入系统的请求速率，防止瞬时流量超过系统处理能力。

它解决的问题是：**系统资源有限，不能让所有请求无条件进入核心链路**。

常见场景：

- 秒杀、大促、热点活动。
- 接口被刷。
- 下游服务能力有限。
- 保护数据库、缓存、第三方接口。

限流会牺牲部分请求体验，但换来的是系统整体稳定。

### 常见限流算法有哪些？

常见算法包括：

| 算法     | 特点                     | 问题或适用场景                         |
| -------- | ------------------------ | -------------------------------------- |
| 固定窗口 | 实现简单                 | 临界点可能出现流量突刺                 |
| 滑动窗口 | 比固定窗口更平滑         | 实现复杂度更高                         |
| 漏桶     | 按固定速率匀速处理请求   | 无法利用空闲时积累处理能力应对突发     |
| 令牌桶   | 平均限速，也允许短暂突发 | 实际业务中更常用，突发上限受桶容量限制 |

![固定窗口计数器算法](https://static001.infoq.cn/resource/image/8d/15/8ded7a2b90e1482093f92fff555b3615.png)

![滑动窗口计数器算法](https://static001.infoq.cn/resource/image/ae/15/ae4d3cd14efb8dc7046d691c90264715.png)

![漏桶算法](https://static001.infoq.cn/resource/image/75/03/75938d1010138ce66e38c6ed0392f103.png)

![令牌桶算法](https://static001.infoq.cn/resource/image/ec/93/eca0e5eaa35dac938c673fecf2ec9a93.png)

令牌桶比漏桶更灵活，因为它允许桶里积累一定令牌，短时间内可以处理突发请求。令牌桶有两个核心参数：填充速率（rate）和桶容量（burst），短时间最大突发量不会超过桶内积累的令牌数。

如果面试官追问"网关限流、接口限流、用户维度限流怎么选"，可以这样答：网关适合统一入口保护，接口维度适合保护高成本接口，用户/IP/租户维度适合防刷和防单个调用方拖垮系统。

### ⭐️固定窗口算法有什么问题？

固定窗口的问题是 **临界突刺**。

比如限制每分钟 100 次请求，如果用户在第 1 分钟最后 1 秒发了 100 次，又在第 2 分钟第 1 秒发了 100 次，从窗口统计看都没超限，但实际上 2 秒内进入了 200 次请求。

这就是固定窗口不够平滑的地方。滑动窗口通过把时间切成更小粒度，可以缓解这个问题。

### 单机限流和分布式限流有什么区别？

单机限流只统计当前实例上的请求，适合单体应用或每个节点独立保护自己的场景。

分布式限流需要多个实例共享限流状态，常见实现方式包括 Redis + Lua、网关限流、Sentinel 集群限流等。

区别在于：

- 单机限流简单，但无法控制全局总 QPS。
- 分布式限流能控制全局流量，但会引入网络开销和一致性问题。

![ShenYu 限流脚本](https://oss.javaguide.cn/github/javaguide/高可用/服务限流详解-固定窗口、滑动窗口、令牌桶、漏桶与分布式限流/shenyu-ratelimit-lua-scripts.png)

Redis + Lua 是分布式限流里很常见的实现方式，原因是 Lua 脚本可以把"读取计数、判断阈值、更新计数"放到一次原子执行里，避免并发下计数不准。它的代价是依赖 Redis 可用性，Redis 宕机、主从切换或网络抖动时，限流可能短时间不准甚至失效，所以生产环境要配合 Redis Sentinel/Cluster，并准备本地限流兜底。

面试加分点：不是所有微服务都必须用分布式限流。如果总配额可以按实例数均分（比如 10 个实例，每个承担 1/10），单机限流反而更简单、延迟更低、不依赖外部存储。

### ⭐️令牌桶和漏桶的核心区别是什么？

两者都能限流，但哲学不同：

- **漏桶**：请求以固定速率流出，不管来了多少请求，处理速度恒定。好处是输出平滑，坏处是突发流量来了也只能慢慢处理，没法利用系统空闲时的处理能力。
- **令牌桶**：令牌以固定速率放入桶中，桶有容量上限。请求来了拿令牌，拿到就处理，拿不到就拒绝或等待。空闲时令牌会积累，短时间突发可以一次性消耗积累的令牌。

核心区别就一个：**令牌桶允许突发，漏桶不允许**。实际业务中大多数场景用令牌桶，因为流量本身就是有波动的，完全匀速处理既不现实也没必要。

### 限流的维度怎么选择？

常见限流维度：

| 维度      | 适用场景                 | 注意点                                 |
| --------- | ------------------------ | -------------------------------------- |
| IP        | 防刷、防攻击             | X-Forwarded-For 可能被伪造，别直接信任 |
| 用户 ID   | 防止单个用户过度消耗资源 | 未登录用户需要回退到 IP 维度           |
| 接口      | 保护高成本接口           | 接口粒度太细可能配置爆炸               |
| 服务/网关 | 统一入口保护             | 粒度粗，可能误杀                       |
| 业务 ID   | 按租户、商户等维度隔离   | 需要业务层配合传递标识                 |

选择原则：**网关做粗粒度保护，服务内做细粒度保护**。不要只在一个层面做限流，否则不是漏了就是误杀了。

### Guava RateLimiter 有哪两种模式？

Guava RateLimiter 提供两种常见模式：

- **平滑突发限流（SmoothBursty）**：令牌按固定速率生成，允许突发。适合大多数普通场景。
- **平滑预热限流（SmoothWarmingUp）**：刚启动时速率较低，经过预热时间后逐步升到稳定速率。适合系统冷启动时数据库连接池还没热、JIT 还没编译完成等场景。

面试中如果被问到"系统刚重启时为什么会有一波超时"，可以提到预热限流：冷启动时缓存是空的，连接池还没建好，如果这时就打满流量，很容易超时。预热限流可以在启动阶段逐步放量，让系统先热起来。

## 降级与熔断

### ⭐️什么是服务降级？

服务降级是当系统负载过高或部分依赖异常时，主动降低非核心功能的服务质量，优先保证核心链路可用。

典型例子：

- 大促时关闭商品推荐，保留下单和支付。
- 评论、排行榜、广告位返回默认值。
- 非核心写操作先写入 MQ，后续异步处理。

降级的核心思想是：**保核心，弃非核心**。

降级不只是"负载太高才触发"，下游服务异常、机房故障、大促预案、运营控制等都可能触发。降级粒度可以从粗到细：服务级 → 页面区块级 → 接口级 → 功能开关级。

### 常见降级方式有哪些？

常见方式包括：

- 页面片段降级：关闭推荐区、广告位等非核心模块。
- 读降级：只读缓存，后端不可用时返回默认值。
- 写降级：先写缓存或 MQ，后续补偿同步。
- 异步降级：非实时操作改为异步处理。
- 页面跳转降级：跳转到静态页或简版页。

降级预案需要提前设计，不应该等故障发生时临时拍脑袋。大型系统通常会建设统一的降级平台，支持按功能开关、接口、服务维度灵活控制降级状态。

### ⭐️什么是熔断？它解决什么问题？

熔断是当下游服务异常或响应过慢时，调用方暂时停止调用下游，直接返回失败或兜底结果，防止故障沿调用链扩散。

它解决的是 **雪崩效应**。

比如服务 A 调用服务 B，服务 B 调用服务 C。服务 C 变慢后，B 的线程被拖住，A 的请求也开始堆积，最终整个链路都被拖垮。熔断就是在发现 C 明显异常后，主动切断对 C 的调用，保护 A 和 B。

![雪崩效应传播](https://oss.javaguide.cn/github/javaguide/高可用/fallback-and-circuit-breaker-avalanche-effect-spread.png)

### 熔断器有哪些状态？

常见状态有 3 个：

- **Closed**：正常状态，请求正常通过。
- **Open**：熔断打开，请求不再调用下游，直接走 fallback。
- **HalfOpen**：半开状态，放少量探测请求检查下游是否恢复。

如果 HalfOpen 探测成功，熔断器回到 Closed；如果失败，继续 Open。

![熔断器状态机](https://oss.javaguide.cn/github/javaguide/高可用/fallback-and-circuit-breaker-fuse-state-machine.png)

Closed 不是"永远安全"，它只是正常放行；Open 不是"下游一定挂了"，它代表调用方基于阈值判断继续调用风险太高；HalfOpen 是恢复探测窗口，不能一下子把全量流量放回去。

面试加分点：Sentinel 1.8.0 之后提供三种熔断策略——慢调用比例、异常比例、异常数。注意 P99 延迟不能直接当熔断条件，熔断看的是在 **一个统计时间窗口内** 慢调用或异常的比例是否超过阈值，而不是单个请求的延迟。

### ⭐️降级和熔断有什么区别？

区别如下：

| 维度     | 降级                       | 熔断                         |
| -------- | -------------------------- | ---------------------------- |
| 关注点   | 主动牺牲非核心功能         | 阻断异常依赖                 |
| 触发方式 | 可以人工触发，也可自动触发 | 通常由失败率、慢调用比例触发 |
| 目标     | 保核心链路                 | 防止故障扩散                 |
| 恢复方式 | 手动恢复或自动恢复         | 通过 HalfOpen 探测恢复       |

一句话区分：**降级是主动降低服务质量，熔断是被下游故障逼出来的链路保护**。

### 超时、重试、熔断、限流、隔离怎么配合？

只设置超时和重试还不够。超时和重试是弹性手段，但如果下游持续异常，重试反而会放大故障。生产环境通常需要多种机制组合使用：

| 机制                        | 职责                 | 关键点                            |
| --------------------------- | -------------------- | --------------------------------- |
| **超时（Timeout）**         | 及时释放等待资源     | 避免请求无限堆积                  |
| **重试（Retry）**           | 处理瞬态失败         | 必须限制次数、退避、加 Jitter     |
| **限流（Rate Limit）**      | 限制进入系统的请求量 | 保护下游不被流量冲垮              |
| **熔断（Circuit Breaker）** | 避免继续打异常下游   | 快速失败，给下游恢复时间          |
| **隔离（Bulkhead）**        | 限制故障影响面       | 线程池 / 信号量隔离，防止级联失败 |

面试中如果被问到"怎么设计一个高可用的调用链"，可以按这个组合关系回答：入口限流 → 超时保护 → 可重试的瞬态错误用重试 + 退避 → 下游持续异常用熔断 → 写操作必须幂等。

### 线程池隔离和信号量隔离有什么区别？

隔离是防止某个下游故障把整个服务拖垮的关键手段。常见的两种隔离策略：

| 维度     | 线程池隔离                   | 信号量隔离                   |
| -------- | ---------------------------- | ---------------------------- |
| 实现方式 | 给下游调用分配独立线程池     | 限制同时执行的请求数         |
| 隔离程度 | 彻底，调用在独立线程中执行   | 轻量，调用在当前线程中执行   |
| 开销     | 线程上下文切换，资源占用较高 | 低开销，不需要额外线程池     |
| 适用场景 | 调用延迟不可控、需要完整隔离 | 调用延迟可控、需要低开销保护 |

Hystrix 默认使用线程池隔离；Sentinel 的并发线程数控制更接近信号量隔离的思路。

线程池隔离的代价不是很多人以为的"GC 扫描"，而是 **上下文切换**。线程多了以后 CPU 在线程间频繁调度，sy 飙高，P99 尾延迟跟着恶化。到底严不严重，得看线程数、CPU sy/us 比例、队列等待时间和 P99 指标，别光凭感觉。

![隔离策略对比](https://oss.javaguide.cn/github/javaguide/高可用/fallback-and-circuit-breaker-isolation-strategy-comparison.png)

### Sentinel 的系统自适应保护是什么？

普通限流通常是手动设置一个阈值，比如 QPS 超过 1000 就限流。但真实系统不是这么简单，CPU、Load、RT、线程数、入口 QPS 都会影响系统是否已经接近极限。

Sentinel 的系统自适应保护从整个系统负载角度判断要不要拒绝部分请求。官方文档里说这个思路受 TCP BBR 启发，目标是在保证系统可靠的前提下维持较高吞吐。可以粗略理解成：

**`当前并发请求数 > 系统最大 QPS × 最小 RT`**

如果当前在途请求已经超过系统估算的承载能力，就开始拒绝一部分流量。系统规则可以按这些指标配置：Load、CPU 使用率、总体 RT、并发线程数、入口 QPS。

注意别把它理解成完整的 TCP BBR——Sentinel 是借鉴思路，结合实时统计和规则阈值做保护，不是像 TCP 那样动态探测带宽、调整拥塞窗口。

### Fallback 设计有哪些常见坑？

Fallback（兜底逻辑）写起来简单，但生产环境踩坑的概率很高：

- **Fallback 里藏远程调用**：兜底方法里又调了另一个服务，如果这个服务也挂了呢？Fallback 应该尽量本地返回，不引入新的远程依赖。
- **返回 null 或空对象不处理**：调用方拿到的 Fallback 结果是 null，后续逻辑空指针异常，比不降级还严重。
- **Fallback 逻辑太复杂**：兜底方法里写了一堆 if-else 和业务逻辑，容易出 Bug 还难测试。Fallback 越简单越好。
- **多个 Fallback 共用同一个缓存**：缓存被打满，所有兜底同时失效。按业务维度隔离缓存，核心链路独立缓存实例。

一句话总结：**Fallback 的目标是让系统"有尊严地失败"，而不是把问题藏起来**。

### Hystrix、Sentinel、Resilience4j 怎么选？

简单建议：

- 新项目使用 Spring Cloud Alibaba，优先考虑 Sentinel。
- 响应式或轻量级项目，可以考虑 Resilience4j。
- 老项目已经使用 Hystrix，可以继续维护，但要规划迁移，因为 Hystrix 已经停止维护。

Sentinel 的优势是限流、熔断、降级、系统自适应保护能力比较完整，并且有控制台支持。需要注意的是，Sentinel 集群限流的 Token Server 需要单独部署，存在可用性和性能瓶颈；如果只做单机实例自保护，单机限流模式反而更简单。

选型时还要看项目栈：Spring Cloud Alibaba 体系下 Sentinel 接入成本低；轻量服务或响应式链路可以考虑 Resilience4j；已经历史使用 Hystrix 的系统通常不建议继续大规模扩展新能力。

面试加分点：Sentinel 中 blockHandler 和 fallback 是不同的概念。blockHandler 处理的是 Sentinel 规则拦截（如限流、熔断触发），fallback 处理的是业务异常。两者不要混用。

## 超时、重试与幂等

### ⭐️为什么所有远程调用都要设置超时？

远程调用可能因为网络抖动、下游慢、连接池耗尽、服务故障等原因一直不返回。如果不设置超时，请求线程会长期阻塞，最终导致连接数、线程数、队列全部被打满。

超时机制的作用是让失败尽快暴露，避免慢请求无限堆积。

![超时机制](https://oss.javaguide.cn/github/javaguide/高可用/timeout-mechanism-overview.png)

常见超时类型：

- **连接超时（Connect Timeout）**：建立 TCP 连接的最长等待时间。
- **读取超时（Read Timeout）**：连接建立后等待响应数据的最长等待时间。
- **获取连接超时**：从连接池拿连接的最长等待时间。

入门时理解这三种就够了，但生产环境还要看客户端是否支持更多维度：DNS 解析超时、TLS 握手超时、Write Timeout、Call Timeout / Deadline（整个调用的总超时）、空闲连接清理超时等。不同 HTTP/RPC 客户端对这些超时字段的覆盖范围不同，配置时必须绑定具体客户端实现的文档。

### 超时时间应该如何设置？

超时时间太短，正常慢请求也会被误杀；太长，又无法及时释放资源。

一般建议：

- 根据接口 P99、P999 延迟设置，而不是拍脑袋定一个固定值。比如 AWS 的经验是：先确定可接受的 false timeout 比例（例如 0.1%），再选择对应延迟百分位（如 P99.9）作为超时起点。
- 结合业务可接受等待时间。
- 区分核心链路和非核心链路。
- 放到配置中心，支持动态调整。

微服务调用链中更推荐传递 **deadline 或 timeout budget**：入口请求有一个总时间预算，每经过一层都要扣除本地处理、排队、网络和下游调用时间。下游超时应小于调用方剩余预算，而不是每层拍脑袋固定 3s、2s、1s。

超时配置动态调整要灰度发布，并观察 P99/P999 延迟、超时率、线程池队列、连接池等待时间和重试量，不能大范围直接推全量。

### ⭐️为什么重试可能导致故障放大？

重试的本意是解决瞬态故障，但如果下游已经过载，大量上游同时重试，会让下游压力更大，形成 **重试风暴**。

重试风险包括：

- 放大下游流量。
- 增加请求延迟。
- 导致重复操作。
- 触发雪崩效应。

所以，重试必须配合超时、限流、熔断、幂等和退避策略一起使用。

### 常见重试策略有哪些？

常见策略：

- 固定间隔重试。
- 线性退避重试。
- 指数退避重试。
- 带随机抖动（Jitter）的指数退避。

分布式系统里更推荐 **带 Jitter 的指数退避**。指数退避能逐步降低重试频率，Jitter 能避免大量客户端在同一时间点一起重试。Jitter 的具体实现可以是 full jitter（完全随机）、equal jitter（等分抖动）或 decorrelated jitter（去相关抖动），目标都是打散多个客户端的同步重试。

![重试前必须先判断：错误类型 + 操作幂等](https://oss.javaguide.cn/github/javaguide/高可用/timeout-and-retry-optimized-retry-idempotency-decision.png)

在线同步请求的重试次数通常要很克制，常见是 1～3 次。异步任务或 MQ 消费可以更多，但必须配合退避、最大重试次数、死信队列、告警和人工补偿。

### ⭐️哪些请求可以重试？哪些不适合重试？

| 分类         | 典型场景                                           | 处理方式                    |
| ------------ | -------------------------------------------------- | --------------------------- |
| **可重试**   | 连接超时、读超时、连接重置、临时 502/503/504       | 配合退避策略重试            |
| **可重试**   | 限流后带 `Retry-After` 的 429                      | 按 `Retry-After` 等待后重试 |
| **谨慎重试** | 支付、下单、库存扣减、发券等写操作                 | 必须有幂等键或业务唯一约束  |
| **不应重试** | 参数错误（400）、权限失败（401/403）、业务规则失败 | 直接返回错误                |
| **不应重试** | 余额不足、库存不足等业务异常                       | 直接返回错误                |

一般只重试超时、连接断开、临时 5xx、限流后明确允许重试的响应；不要重试参数校验失败、权限失败、业务规则失败、明确的 4xx，以及无法保证幂等的写操作。

写操作如果要重试，必须先做好幂等。

### 什么是重试预算（Retry Budget）？

**重试预算（Retry Budget）** 是一种有效的规避策略：限制在一定时间窗口内的重试次数占总请求数的比例，如不超过 10%。落地时可以按调用方、接口或下游维度统计原始请求数和重试请求数，当重试比例超过预算时，后续请求快速失败或只允许首试，不再重试。

### 什么是幂等？

幂等指同一个操作执行一次和执行多次，最终结果一致。

从 HTTP 语义上看，RFC 9110 定义 PUT、DELETE 以及 safe methods（GET、HEAD、OPTIONS、TRACE）为幂等方法。POST 默认不具备幂等语义，但可以通过幂等键、业务唯一约束等方式实现业务幂等。但协议语义不等于服务端实现一定安全，涉及创建订单、扣款、发券、发消息等副作用操作时，服务端仍然需要显式设计幂等。

常见幂等方案：

- 请求唯一 ID（幂等键）。
- 数据库唯一索引。
- Redis 去重。
- 乐观锁版本号。
- 状态机流转控制。
- 业务防重表。

![幂等请求处理主流程](https://oss.javaguide.cn/github/javaguide/高可用/ha-interview-idempotency-flow.png)

幂等的难点不在"识别重复请求"这句话，而在并发下第一次请求和重复请求同时到达时，如何保证只有一个请求真正执行副作用操作。常见解法是利用数据库唯一索引或防重表：先插入幂等记录，插入成功的请求执行业务，插入失败的重复请求查询已有结果返回；插入幂等记录和业务操作最好放在同一个事务中。

面试加分点：赋值更新（如 `set status = "PAID"`）比累加更新（如 `set balance = balance - 100`）更容易做到幂等，累加更新必须额外控制重复执行。

### ⭐️支付接口如何保证幂等？

可以这样设计：

1. 客户端或服务端生成唯一支付请求号。
2. 服务端用请求号建立唯一索引或幂等记录。
3. 第一次请求执行支付流程。
4. 重复请求直接返回第一次处理结果。
5. 支付状态通过状态机控制，只允许合法状态流转。

核心原则是：**扣款、入账、发券这类副作用操作，必须能识别重复请求**。

状态机也很重要。比如支付单只能从 `INIT` 流转到 `PAYING`，再流转到 `SUCCESS` 或 `FAILED`，不能让重复通知把已经成功的支付单再次扣款，也不能让失败状态覆盖成功状态。

幂等设计完成后，建议通过并发压测、重试测试、异常测试、数据校验等方式验证，不能只在正常流程下测一下就上线。

### 幂等和去重有什么区别？

这两个概念经常被混用，但侧重点不同：

- **去重**：防止重复请求到达服务端。比如消息队列的 dedup 机制、客户端的防重复提交。
- **幂等**：允许重复请求到达，但保证多次执行的结果和一次执行一致。

去重是"不让它来"，幂等是"来了也不怕"。生产中两者经常配合使用：先尽量在入口去重，兜底还是靠幂等。因为去重不可能 100% 挡住（比如网络分区导致去重记录丢失），最终还是得靠服务端幂等保证数据安全。

### ⭐️Token 机制怎么做幂等？

Token 机制是防重复提交的常见方案，基本流程：

1. 客户端先请求一个 Token（服务端生成并存入 Redis，设过期时间）。
2. 客户端提交业务请求时携带这个 Token。
3. 服务端收到请求后，验证并消费 Token（原子操作）。
4. Token 消费成功后执行业务逻辑。

关键问题是 **Token 消费和业务执行谁先谁后**：

- 先删 Token 再执行业务：如果业务执行失败，Token 已经没了，客户端重试会被拒。需要在业务失败时把 Token 放回去。
- 先执行业务再删 Token：如果业务执行成功但删 Token 失败，客户端重试会再执行一次业务。必须保证业务本身幂等。

推荐做法是 **先原子消费 Token，再执行业务**。Redis 6.2.0 及以上版本可以使用 `GETDEL` 命令，低版本可以用 Lua 脚本保证"校验 + 删除"的原子性。如果业务执行失败，再根据情况决定是否恢复 Token。

### 悲观锁做幂等有什么坑？

用 `SELECT ... FOR UPDATE` 做幂等控制时，常见坑：

- **RR 隔离级别下的 Next-Key Lock**：MySQL 在 RR 隔离级别下，`SELECT ... FOR UPDATE` 可能会锁住不只是一行，而是一个范围（Next-Key Lock = Gap Lock + Record Lock）。如果查询条件不是唯一索引，可能锁住大量记录，导致并发性能骤降。
- **死锁风险**：多个请求以不同顺序获取锁，可能互相等待，形成死锁。
- **锁超时**：如果事务持有锁的时间太长（比如事务里还有远程调用），其他请求会等待超时。

建议：用悲观锁做幂等时，查询条件必须命中唯一索引，事务尽量短，不要在事务里做远程调用。更好的做法是优先用唯一索引或防重表替代悲观锁。

## 性能测试与故障治理

### 性能测试常见指标有哪些？

常见指标包括：

- **响应时间 RT**：请求从发出到收到响应的时间。
- **QPS**：每秒查询数。
- **TPS**：每秒事务数。
- **并发数**：同一时间正在处理的请求数量。
- **吞吐量**：单位时间内系统处理的数据量。
- **错误率**：失败请求占比。
- **资源使用率**：CPU、内存、磁盘、网络、连接池、线程池等。

QPS 通常用于衡量读接口或网关层流量；TPS 更适合衡量一次完整业务事务（如下单包含扣库存、创建订单、写流水等）。面试中两者经常被混用，但主动区分会更严谨。

![性能测试指标分类](https://oss.javaguide.cn/github/javaguide/高可用/ha-interview-performance-metrics.png)

面试里不要只说平均 RT，P95、P99 更能反映长尾延迟。

### ⭐️性能测试、负载测试、压力测试、稳定性测试有什么区别？

区别如下：

| 类型       | 目标                           |
| ---------- | ------------------------------ |
| 性能测试   | 评估系统在预期负载下的性能表现 |
| 负载测试   | 逐步增加负载，观察性能变化     |
| 压力测试   | 找到系统极限和崩溃点           |
| 稳定性测试 | 长时间运行，观察是否有资源泄漏 |

如果面试官问"怎么证明系统能扛住大促"，只回答压测工具不够，还要说明压测模型、流量比例、数据准备、监控指标和瓶颈定位方法。

![性能压测主流程](https://oss.javaguide.cn/github/javaguide/高可用/ha-interview-performance-test-flow.png)

### 如何做容量评估？

容量评估一般需要：

1. 估算峰值 QPS、TPS、并发数。
2. 梳理核心接口和流量比例。
3. 准备接近真实的数据量。
4. 通过压测得到单机能力和集群能力。
5. 预留安全水位，比如只使用 60% 到 70% 的容量。
6. 对数据库、缓存、MQ、第三方接口分别评估瓶颈。

容量评估不是只看应用服务器，很多系统真正的瓶颈在数据库、缓存热点、连接池或下游接口。

### ⭐️缓存穿透、缓存击穿、缓存雪崩分别是什么？

这是缓存高可用的三个经典问题：

| 问题     | 触发条件                                  | 常见方案                                       |
| -------- | ----------------------------------------- | ---------------------------------------------- |
| **穿透** | 查询一个数据库里也不存在的数据            | 布隆过滤器 / 缓存空值                          |
| **击穿** | 某个热点 Key 过期，大量请求瞬间打到数据库 | 互斥锁 / 永不过期 + 异步刷新                   |
| **雪崩** | 大量 Key 同时过期，或者缓存节点宕机       | 过期时间加随机抖动 / 缓存高可用集群 / 限流降级 |

面试中容易混淆的是击穿和雪崩。区分关键：**击穿是一个 Key，雪崩是一批 Key**。击穿是"狙击手"，雪崩是"地毯式轰炸"。

缓存穿透用布隆过滤器的代价是会有一定的误判率（说存在不一定存在，说不存在一定不存在），而且布隆过滤器不支持删除。如果数据集变化频繁，要考虑用 Counting Bloom Filter 或定期重建。

### 什么是故障演练？

故障演练（Chaos Engineering / 混沌工程）是 **主动在生产或预发环境注入故障，验证系统的容错和恢复能力**。

和普通压测不同，压测验证的是"系统能扛多少流量"，故障演练验证的是"系统出了问题能不能自动恢复"。

常见演练场景：

- 随机关停一个服务实例，看流量是否自动切换。
- 给某个接口注入延迟，看超时和熔断是否生效。
- 模拟网络分区，看脑裂防护是否工作。
- 模拟 Redis 主节点宕机，看 Sentinel 切换耗时和数据丢失。

故障演练的目的是 **在真正的故障发生之前，提前发现系统的薄弱环节**。很多公司只在出事后才知道"原来我们的 Sentinel 配置有问题"或者"原来超时是 30 秒而不是 3 秒"，这就是缺少故障演练的代价。

### ⭐️如何设计一个高可用系统？

可以按这条主线回答：

1. **识别核心链路**：明确哪些功能必须可用，哪些功能可以降级。
2. **消除单点故障**：服务、数据库、缓存、MQ、入口网关都要考虑冗余。
3. **控制入口流量**：限流、排队、削峰，避免流量打穿系统。
4. **保护下游依赖**：超时、重试、熔断、隔离，避免故障扩散。
5. **保证写操作安全**：幂等、防重、状态机，避免重复执行。
6. **准备降级预案**：非核心功能可关闭，核心链路优先保障。
7. **建立观测体系**：监控、日志、Trace、告警、压测和故障演练。

高可用设计的核心不是承诺系统不会挂，而是让故障发生时影响可控、恢复可控、数据风险可控。

![高可用系统设计主线](https://oss.javaguide.cn/github/javaguide/高可用/ha-interview-ha-design-flow.png)

### 超时和重试上线后，应该关注哪些观测指标？

光配置好超时和重试还不够，上线后必须靠指标验证。关键指标：

| 指标类别 | 具体指标                                   |
| -------- | ------------------------------------------ |
| 请求量   | 原始请求 QPS、重试请求 QPS、重试比例       |
| 延迟     | P99 / P999 延迟、超时率                    |
| 成功率   | 最终成功率、首次成功率                     |
| 下游健康 | 下游 5xx 数量、限流次数、熔断器状态        |
| 资源     | 线程池队列深度、连接池等待时间、活跃连接数 |
| 重试预算 | Retry Budget 消耗比例                      |

其中 **首次成功率 vs 最终成功率** 的差值特别值得看：如果首次成功率很低但最终成功率还行，说明系统在靠重试续命，下游可能已经不太健康了。这不是"重试做得好"，而是"问题被重试掩盖了"。


---

---

<!-- source: 超时和重试机制详解-超时设置、指数退避、随机抖动、重试风暴与幂等.md -->

## [2] 超时和重试机制详解：超时设置、指数退避、随机抖动、重试风暴与幂等

---
title: 超时和重试机制详解：超时设置、指数退避、随机抖动、重试风暴与幂等
description: 超时与重试机制详解，讲解连接超时、读取超时、超时时间设置、固定间隔重试、线性退避、指数退避、随机抖动、重试风暴、雪崩效应、幂等性设计，以及 Spring Retry、Resilience4j 等 Java 重试框架。
category: 高可用
icon: "mdi:reload"
tag:
  - 超时重试
  - 高可用
head:
  - - meta
    - name: keywords
      content: 超时机制,重试机制,超时设置,连接超时,读取超时,指数退避,随机抖动,重试风暴,雪崩效应,幂等性,Spring Retry,Resilience4j,超时重试面试题
---

由于网络抖动、硬件故障、进程异常、依赖服务不可用等问题的不确定性，我们的系统或者服务永远不可能保证时刻都是可用的状态。

为了最大限度地减小系统或者服务出现故障之后带来的影响，我们需要用到 **超时（Timeout）** 和 **重试（Retry）** 机制。

超时和重试的核心思想确实不难理解，但在生产环境中正确使用它们却有不少门道。你平时接触到的绝大部分涉及远程调用的系统或者服务都会应用超时和重试机制。尤其是对于微服务系统来说，正确设置超时和重试非常重要。单体服务通常只涉及数据库、缓存、第三方 API、中间件等的网络调用，而微服务系统内部各个服务之间还存在着网络调用。

## 超时机制

![超时机制](https://oss.javaguide.cn/github/javaguide/高可用/timeout-mechanism-overview.png)

### 什么是超时机制？

**超时机制** 说的是当一个请求超过指定的时间（比如 1s）还没有被处理的话，这个请求就会直接被取消并抛出指定的异常或者错误（比如 `504 Gateway Timeout`）。

我们平时接触到的超时可以简单分为下面 2 种：

| 超时类型                        | 说明                                               | 建议值          |
| ------------------------------- | -------------------------------------------------- | --------------- |
| **连接超时（Connect Timeout）** | 客户端与服务端建立 TCP 连接的最长等待时间          | 1000ms ~ 5000ms |
| **读取超时（Read Timeout）**    | 连接已建立后，客户端等待对端返回数据的最长等待时间 | 1000ms ~ 3000ms |

入门时可以先理解连接超时和读取超时，但 **生产环境还要看客户端是否支持更多维度的超时配置**：

| 超时阶段                | 说明                               |
| ----------------------- | ---------------------------------- |
| DNS 解析超时            | 域名解析的最长等待时间             |
| 连接池获取连接超时      | 从连接池获取可用连接的最长等待时间 |
| Connect Timeout         | TCP 建立连接的最长等待时间         |
| TLS 握手超时            | TLS/SSL 握手阶段的最长等待时间     |
| Write Timeout           | 请求体写入的最长等待时间           |
| Read / Response Timeout | 等待响应数据读取的最长等待时间     |
| Call Timeout / Deadline | 整个调用的总超时时间，包含所有阶段 |
| 空闲连接清理超时        | 连接池中空闲连接的最大存活时间     |

> 不同 HTTP/RPC 客户端对 read timeout、response timeout、call timeout 的覆盖范围不同，配置时必须绑定具体客户端实现的文档。

### 为什么需要超时机制？

如果没有设置超时的话，就可能会导致 **服务端连接数爆炸** 和 **大量请求堆积** 的问题。

这些堆积的连接和请求会消耗系统资源，影响新收到的请求的处理。严重的情况下，甚至会拖垮整个系统或者服务。

> 我之前在实际项目就遇到过类似的问题，整个网站无法正常处理请求，服务器负载直接快被拉满。后面发现原因是项目超时设置错误加上客户端请求处理异常，导致服务端连接数接近 40 万，这么多堆积的连接直接拖垮了整个系统。

### 超时时间应该如何设置？

超时时间应该设置多长，是一个需要结合业务场景判断的问题。**超时值设置太高或者太低都有风险**：

| 设置方式     | 风险                                                                                 |
| ------------ | ------------------------------------------------------------------------------------ |
| **设置太高** | 降低超时机制的有效性，系统依然可能出现大量慢请求堆积的问题                           |
| **设置太低** | 在系统处理速度变慢时（如请求突然增多），大量请求超时重试，加重系统压力，可能导致雪崩 |

通常情况下，我们建议：

- **读取超时**：对于延迟敏感型在线服务的内部 RPC 调用，可以先根据历史 **P99/P999 延迟**、核心链路 **SLO** 和可接受的误超时率设置初始值，再压测调整。比如 AWS 的经验是：先确定可接受的 false timeout 比例（例如 0.1%），再选择对应延迟百分位（如 P99.9）作为超时起点。
- **连接超时**：要按网络环境区分。同机房内网调用通常应较短；跨地域、公网、代理链路、TLS 冷连接可能需要更长。连接池场景还要区分首次建连和复用连接，建议在 **1000ms ~ 5000ms** 之内。

**没有银弹！** 超时值具体该设置多大，还是要根据实际项目的需求和情况慢慢调整优化得到。

在微服务调用链中，还要遵循一个原则：**下游超时要小于上游超时**，并给网络开销和本地处理预留余量。

更推荐的做法是传递 **deadline 或 timeout budget**：入口请求有一个总时间预算，每经过一层都要扣除本地处理、排队、网络和下游调用时间。下游超时应小于调用方剩余预算，而不是每层拍脑袋固定 3s、2s、1s。否则上游已经超时返回，下游还在继续执行无效请求，容易放大资源浪费。

![超时预算在微服务链路中的传递](https://oss.javaguide.cn/github/javaguide/高可用/timeout-and-retry-optimized-timeout-budget-chain.png)

更进一步，参考 [美团的 Java 线程池参数动态配置](https://tech.meituan.com/2020/04/02/java-pooling-pratice-in-meituan.html) 思想，我们也可以将超时弄成 **可配置化的参数** 而不是固定的，比较简单的一种办法就是将超时的值放在配置中心中。这样的话，我们就可以根据系统或者服务的状态动态调整超时值了。

> 超时配置动态调整要灰度发布，并观察 P99/P999 延迟、超时率、线程池队列、连接池等待时间和重试量，不能大范围直接推全量。

### 超时、重试、熔断、限流的组合关系

只设置超时和重试还不够。超时和重试是弹性手段，但如果下游持续异常，重试反而会放大故障。生产环境通常需要 **超时 + 重试 + 熔断 + 限流** 组合使用：

| 机制                        | 职责                 | 关键点                            |
| --------------------------- | -------------------- | --------------------------------- |
| **超时（Timeout）**         | 及时释放等待资源     | 避免请求无限堆积                  |
| **重试（Retry）**           | 处理瞬态失败         | 必须限制次数、退避、加 Jitter     |
| **限流（Rate Limit）**      | 限制进入系统的请求量 | 保护下游不被流量冲垮              |
| **熔断（Circuit Breaker）** | 避免继续打异常下游   | 快速失败，给下游恢复时间          |
| **隔离（Bulkhead）**        | 限制故障影响面       | 线程池 / 信号量隔离，防止级联失败 |

## 重试机制

![重试机制](https://oss.javaguide.cn/github/javaguide/高可用/retry-mechanism-overview.png)

### 什么是重试机制？

**重试机制** 一般配合超时机制一起使用，指的是 **对同一业务意图再次发起调用，来避免瞬态故障和偶然性故障**。

- **瞬态故障**：某一瞬间系统偶然出现的故障，并不会持久。
- **偶然性故障**：在某些情况下偶尔出现的故障，频率通常较低。

重试是对同一业务意图再次发起调用，它不一定是字节级完全相同的请求。因此涉及签名、时间戳、请求体流、幂等键时，要保证重试请求仍然合法且可识别为同一业务操作。

重试的核心思想是 **通过消耗额外资源来尽可能提高请求被成功处理的概率**。在瞬态故障频率很低、客户端数量有限的场景下，重试带来的额外负载通常可控；但当故障率升高或大量客户端同时触发重试时，重试流量可能成为压垮下游系统的最后一击，也就是后文要讨论的 **重试风暴**。

### 常见的重试策略有哪些？

常见的重试策略对比如下：

| 策略                     | 说明                              | 优点                   | 缺点                                     | 适用场景                       |
| ------------------------ | --------------------------------- | ---------------------- | ---------------------------------------- | ------------------------------ |
| **固定间隔重试**         | 每次重试间隔相同（如每隔 1s）     | 实现简单               | 可能造成重试风暴                         | 目标系统恢复时间稳定可预测     |
| **线性退避重试**         | 间隔线性增长（如 1s、2s、3s）     | 比固定间隔更温和       | 增长速度较慢                             | 一般场景                       |
| **指数退避重试**         | 间隔指数增长（如 1s、2s、4s、8s） | 比固定间隔更温和       | 多客户端仍可能同步重试，等待时间可能过长 | 目标系统恢复时间较长或不可预测 |
| **带 Jitter 的指数退避** | 指数退避基础上加随机抖动          | 避免多个客户端同时重试 | 实现稍复杂                               | 分布式系统推荐                 |

**分布式系统里通常优先使用带 Jitter 的指数退避策略**。Jitter 的具体实现可以是 full jitter（完全随机）、equal jitter（等分抖动）或 decorrelated jitter（去相关抖动），目标都是打散多个客户端的同步重试。

![四种重试策略时间线对比](https://oss.javaguide.cn/github/javaguide/高可用/timeout-and-retry-optimized-retry-strategies-timeline.png)

### 重试的次数如何设置？

重试的次数不宜过多，否则依然会对系统负载造成比较大的压力。

**在线同步请求的重试次数通常要很克制，常见是 1～3 次**。比如说我们要重试 3 次的话：

- 第 1 次请求失败后，等待 1 秒再进行重试
- 第 2 次请求失败后，等待 2 秒再进行重试
- 第 3 次请求失败后，等待 4 秒再进行重试

异步任务或 MQ 消费可以更多，但必须配合退避、最大重试次数、死信队列、告警和人工补偿。

重试次数不是越多越好。假设读取超时为 1.5s，重试 3 次，并使用 1s、2s、4s 的指数退避，最坏情况下总耗时约为 `1.5s × 4 + 1s + 2s + 4s = 13s`。对于在线请求，这个尾部延迟可能已经不可接受。因此，读操作可以相对积极地重试，写操作必须配合幂等设计，非关键链路也可以选择快速失败。

### 只重试可重试错误

重试落地最关键的一步是 **区分可重试错误和不可重试错误**。盲目重试会浪费资源甚至加剧问题：

| 分类         | 典型场景                                           | 处理方式                    |
| ------------ | -------------------------------------------------- | --------------------------- |
| **可重试**   | 连接超时、读超时、连接重置、临时 502/503/504       | 配合退避策略重试            |
| **可重试**   | 限流后带 `Retry-After` 响应头的 429                | 按 `Retry-After` 等待后重试 |
| **谨慎重试** | 支付、下单、库存扣减、发券等写操作                 | 必须有幂等键或业务唯一约束  |
| **不应重试** | 参数错误（400）、权限失败（401/403）、业务规则失败 | 直接返回错误                |
| **不应重试** | 余额不足、库存不足等业务异常                       | 直接返回错误                |

一般只重试超时、连接断开、临时 5xx、限流后明确允许重试的响应；不要重试参数校验失败、权限失败、业务规则失败、明确的 4xx，以及无法保证幂等的写操作。

![重试前必须先判断：错误类型 + 操作幂等](https://oss.javaguide.cn/github/javaguide/高可用/timeout-and-retry-optimized-retry-idempotency-decision.png)

### 重试的风险有哪些？

重试机制虽然能提高系统的可用性，但使用不当也会带来风险：

| 风险         | 说明                                         | 规避方法                     |
| ------------ | -------------------------------------------- | ---------------------------- |
| **重试风暴** | 大量客户端同时重试，进一步压垮下游服务       | 使用带 Jitter 的指数退避策略 |
| **雪崩效应** | 重试导致上游服务也开始超时重试，形成连锁反应 | 设置重试预算、熔断机制       |
| **重复操作** | 非幂等操作被重复执行，导致数据不一致         | 确保操作幂等性               |
| **资源浪费** | 对永久性故障进行无意义的重试                 | 区分可重试错误和不可重试错误 |

**重试预算（Retry Budget）** 是一种有效的规避策略：限制在一定时间窗口内的重试次数占总请求数的比例，如不超过 10%。落地时可以按调用方、接口或下游维度统计原始请求数和重试请求数，当重试比例超过预算时，后续请求快速失败或只允许首试，不再重试。

![重试风暴：请求量级联放大](https://oss.javaguide.cn/github/javaguide/高可用/timeout-and-retry-optimized-retry-storm-cascade.png)

### 重试为什么必须考虑幂等？

超时和重试机制在实际项目中使用的话，需要注意保证 **同一操作执行一次和执行多次对系统状态产生的影响相同**，这就是幂等性。去重是防止重复执行，幂等是允许重复请求到达但保证结果一致，二者经常配合使用。

什么情况下会出现一个请求被多次执行呢？客户端等待服务端完成请求超时，但此时服务端已经执行了请求，只是由于短暂的网络波动导致响应在发送给客户端的过程中延迟了。

> 举个例子：用户支付购买某个课程，结果用户支付的请求由于重试的问题导致用户购买同一门课程支付了两次。对于这种情况，我们在执行用户购买课程的请求的时候需要判断一下用户是否已经购买过。这样的话，就不会因为重试的问题导致重复购买了。

实现幂等的常见方法：

| 方法               | 说明                                   | 适用场景         |
| ------------------ | -------------------------------------- | ---------------- |
| **唯一请求 ID**    | 每个请求携带唯一 ID，服务端去重        | 通用场景         |
| **数据库唯一约束** | 利用数据库唯一索引防止重复插入         | 创建类操作       |
| **乐观锁**         | 通过版本号控制更新                     | 更新类操作       |
| **状态机**         | 通过状态流转控制，已处理的状态不再处理 | 订单、支付等场景 |

从 HTTP 语义上看，RFC 9110 定义 PUT、DELETE 以及 safe methods（GET、HEAD、OPTIONS、TRACE）为幂等方法。POST 默认不具备幂等语义，但可以通过幂等键、业务唯一约束等方式实现业务幂等。但协议语义不等于服务端实现一定安全，涉及创建订单、扣款、发券、发消息等副作用操作时，服务端仍然需要显式设计幂等。

### Java 中如何实现重试？

如果要手动编写代码实现重试逻辑的话，可以通过 `for` / `while` 循环或者递归实现。不过，一般不建议自己动手实现，有很多第三方开源库提供了更完善的重试机制实现：

| 框架                            | 特点                                 | 最新版本           | 适用场景                                                                     |
| ------------------------------- | ------------------------------------ | ------------------ | ---------------------------------------------------------------------------- |
| **Spring Retry**                | Spring 生态，注解驱动，配置简单      | 2.0.12             | Spring Boot 2.x/3.x 项目                                                     |
| **Spring Framework 7 内置重试** | 原生内置 `@Retryable`，无需额外依赖  | Spring Framework 7 | Spring Boot 4.x 项目                                                         |
| **Resilience4j**                | 轻量级，函数式风格，支持熔断、限流等 | 2.4.0              | 微服务项目                                                                   |
| **Failsafe**                    | 零依赖，支持异步重试、超时、熔断等   | 3.3.2              | 需要细粒度控制的场景                                                         |
| **Guava Retrying**              | 灵活的重试策略配置                   | 2.0.0              | 通用 Java 项目（⚠️ 已长期停更，非 Guava 官方核心模块，使用前需评估维护状态） |

#### Spring Retry 示例

使用 Spring Retry 的简单示例：

```java
@Configuration
@EnableRetry
public class RetryConfig {
}

@Retryable(
    retryFor = {RestClientException.class},
    maxAttempts = 3,
    backoff = @Backoff(delay = 1000, multiplier = 2)
)
public String callRemoteService(String requestId) {
    return remoteClient.call(requestId);
}

@Recover
public String recover(RestClientException e, String requestId) {
    // 重试耗尽后的兜底逻辑
    return "fallback";
}
```

`@Recover` 的第一个参数为异常类型，后续参数与 `@Retryable` 方法参数一致，Spring Retry 通过参数类型匹配恢复方法。

需要注意的是：

- `@Retryable` 基于 Spring AOP 代理，同一个类内部通过 `this.method()` 调用不会触发重试，必须通过 Spring 管理的代理对象调用。
- **Spring Boot 3.x / Spring Framework 6** 体系下，优先确认 Spring Retry 2.x 与项目 Spring 版本、Java 17+ 版本的兼容性，不要混用旧版。
- **Spring Boot 4.x / Spring Framework 7** 开始，重试能力已内置到 `spring-core` 中，使用 `@EnableResilientMethods` 激活，无需额外引入 `spring-retry` 依赖。Spring Retry 项目已进入维护模式（maintenance only），不再接受新特性。

#### Resilience4j Retry 示例

```java
RetryConfig config = RetryConfig.custom()
    .maxAttempts(3)
    .waitDuration(Duration.ofMillis(1000))
    .retryOnException(e -> e instanceof SocketTimeoutException
        || e instanceof ConnectException)
    .ignoreExceptions(BusinessException.class, AuthException.class)
    .intervalFunction(IntervalFunction.ofExponentialBackoff(1000, 2))
    .build();

Retry retry = Retry.of("remoteService", config);

// 获取重试事件用于监控
retry.getEventPublisher()
    .onRetry(event -> log.warn("Retry attempt {}", event.getNumberOfRetryAttempts()));

String result = Retry.decorateSupplier(retry, () -> remoteClient.call(requestId))
    .get();
```

当 Retry 与 CircuitBreaker 组合使用时，要注意装饰器的顺序影响统计口径：`Retry.decorateSupplier(CircuitBreaker.decorateSupplier(supplier))` 意味着重试成功不会打开熔断器，而反过来包装则每次重试都经过熔断器统计。

## 线上观测指标

超时和重试上线后必须靠指标验证，否则很难发现重试风暴等问题。以下是关键的观测指标：

| 指标类别 | 具体指标                                   |
| -------- | ------------------------------------------ |
| 请求量   | 原始请求 QPS、重试请求 QPS、重试比例       |
| 延迟     | P99 / P999 延迟、超时率                    |
| 成功率   | 最终成功率、首次成功率                     |
| 下游健康 | 下游 5xx 数量、限流次数、熔断器状态        |
| 资源     | 线程池队列深度、连接池等待时间、活跃连接数 |
| 重试预算 | Retry Budget 消耗比例                      |

## 参考

- 微服务之间调用超时的设置治理：<https://www.infoq.cn/article/eyrslar53l6hjm5yjgyx>
- 超时、重试和抖动回退（AWS Builders Library）：<https://aws.amazon.com/cn/builders-library/timeouts-retries-and-backoff-with-jitter/>
- AWS Architecture Blog - Exponential Backoff and Jitter：<https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/>
- RFC 9110 - HTTP Semantics：<https://www.rfc-editor.org/rfc/rfc9110>

<!-- @include: @article-footer.snippet.md -->


---

---

<!-- source: 服务降级与熔断详解-Fallback、熔断器状态机与 Sentinel Hystrix Resilience4j 选型.md -->

## [3] 服务降级与熔断详解：Fallback、熔断器状态机与 Sentinel / Hystrix / Resilience4j 选型

---
title: 服务降级与熔断详解：Fallback、熔断器状态机与 Sentinel / Hystrix / Resilience4j 选型
description: 服务降级与熔断机制详解，讲解 Fallback 兜底、降级开关、熔断器 Closed/Open/Half-Open 状态机、雪崩效应、隔离策略，以及 Sentinel、Hystrix、Resilience4j 的选型对比。
category: 高可用
icon: "mdi:electric-switch"
tag:
  - 服务降级
  - 熔断
head:
  - - meta
    - name: keywords
      content: 服务降级,熔断器,熔断机制,Fallback,熔断器状态机,Sentinel,Hystrix,Resilience4j,限流降级熔断区别,雪崩效应,线程池隔离,信号量隔离,高可用面试题
---

在微服务架构里，一个请求往往要经过好几个服务的调用链。如果链路上某个服务出了问题——比如响应变慢、超时甚至直接挂掉——很容易把上游的资源也拖垮，最后演变成整条链路雪崩。服务降级和熔断就是应对这类问题的两道防线：降级负责在系统压力大的时候主动"丢车保帅"，熔断负责在下游持续异常的时候及时"断路"止损。

这篇文章会把降级和熔断的核心原理讲清楚，包括 Fallback 兜底、降级开关、熔断器状态机、隔离策略，以及 Sentinel、Hystrix、Resilience4j 的选型对比。

## 什么是降级？

服务降级，说白了就是：**系统快扛不住的时候，先牺牲不重要的功能，把资源留给核心链路。**

比如电商大促时，推荐模块、广告位、活动氛围图这些非核心功能可以先关掉，但下单、支付、库存扣减这些链路必须尽量保住。用户少看一个推荐还能接受，但下不了单就是真事故。

所以，降级是一套提前设计好的兜底方案，不是系统挂了以后随便返回个默认值。什么时候触发、关哪些功能、返回什么内容、怎么恢复，都应该提前想清楚。

### 降级一般在什么情况下触发？

很多人会把降级理解成“机器负载太高才降级”，其实不止这一种情况。

常见触发场景有几类：

- 系统整体压力太大，比如 CPU 飙高、线程池打满、接口响应时间明显变长；
- 某个下游服务异常，比如库存服务、价格服务、推荐服务突然大量超时；
- 某个机房、区域或网络链路出问题；
- 大促、秒杀、活动上线前，提前按预案关闭部分非核心功能；
- 运营临时需要控制某些功能入口。

不管触发原因是什么，降级的核心目标都一样：**保核心，弃非核心。**

### 降级可以降到什么粒度？

降级的粒度可以粗，也可以细。

粗一点，可以直接降级整个服务。比如推荐服务异常时，所有推荐结果都返回空列表。

细一点，可以只降级页面里的某个区块。比如商品详情页还正常展示，但“猜你喜欢”区域先隐藏。

再细一点，可以只降级某个接口、某个功能开关，甚至某一类用户、某一个业务场景。

实际项目里，通常会给功能分优先级。比如：

- 推荐、广告、排行榜：优先级较低，出问题可以先关；
- 商品详情、购物车：优先级较高，尽量保；
- 下单、支付、库存：核心链路，最后才考虑降级。

这里的 L0-L4、1-10 级都只是团队内部约定，不是行业统一标准。关键不在于怎么命名，而是要提前分清楚：**哪些功能可以牺牲，哪些功能必须保。**

### 降级方式有哪些？

#### 1. 延迟处理

有些操作没必要同步完成，可以先放到 MQ 里慢慢处理。

比如评论后发积分、统计用户行为、生成报表，这类操作即使晚几秒完成，用户一般也感知不到。主流程只要先返回成功，后面的事情交给异步任务处理即可。

但这里有个坑：MQ 也可能积压。如果消费者已经处理不过来了，生产者还一直重试，反而会把系统打得更严重。所以重试要加退避和随机抖动，必要时还要限流。

#### 2. 页面片段降级

这是最直观的一种方式：页面主体保留，把非核心区块关掉。

比如商品详情页里，商品标题、价格、库存要保；推荐区、广告位、活动挂件可以先隐藏。

这种方式简单有效，但前提是你提前做好了开关和兜底逻辑。真出问题时再改代码、再发版，基本就来不及了。

#### 3. 接口兜底降级

页面里有些接口是异步加载的，比如配送时效、价格预测、推荐列表。它们如果超时，可以直接返回默认值或缓存值。

比如配送时效接口异常时，可以先展示“预计 2-3 天送达”；推荐接口异常时，可以返回缓存里的热门商品。

这里要注意一点：兜底数据最好提前准备好。不要等接口已经挂了，才临时去查数据库或重新生成缓存，那样很可能把故障继续放大。

#### 4. 页面跳转降级

如果完整页面太重，可以把用户导到一个简版页面或静态页面。

比如大促活动页访问量太大时，可以临时切到静态活动页；系统维护时，可以跳到维护提示页。

这种方案看起来简单，但一定要提前准备好静态页、路由规则和切换开关。线上出事后再临时做，基本不现实。

#### 5. 写降级

写降级适合一些“可以晚一点落库”的场景。

比如积分发放、消息通知、库存流水这类操作，可以先写 Redis、消息表或本地持久化队列，再由 MQ 或定时任务慢慢同步到数据库。

但写降级的代价也比较明显：你要处理最终一致性问题。比如消息有没有丢、数据有没有重复写、同步失败后怎么补偿、对账怎么做，这些都要提前设计。

尤其要注意，**纯内存队列不适合保存关键数据**。节点一重启，数据就没了。

#### 6. 读降级

读降级通常是“只读缓存，不再访问后端服务”。

比如商品详情、店铺信息、热门榜单这种读多写少的数据，就很适合做缓存兜底。后端服务异常时，先返回缓存里的旧数据，至少页面还能打开。

如果缓存也没命中，就不要继续硬调下游了。可以直接返回默认值、空结果或降级页。否则用户一次请求可能会把一串后端服务都拖进去。

### 降级开关怎么做？

降级必须能快速打开和关闭。不能每次都靠改代码、发版、重启。

常见方案有这些：

| **方案**        | **特点**                 | **适合场景**                 |
| --------------- | ------------------------ | ---------------------------- |
| 配置文件 + 重启 | 简单，但生效慢           | 非紧急、很少变更的开关       |
| 数据库开关表    | 可以做审计，但实时性一般 | 需要记录谁改了、什么时候改的 |
| 配置中心        | 实时性好，生产环境常用   | 核心降级开关、动态开关       |
| Redis 开关      | 实现轻量，接入快         | 简单业务、临时控制           |

生产环境里，更推荐用 Nacos、Apollo 这类配置中心做降级开关。它们比“改配置文件再重启”可靠得多，也更适合应急场景。

不过，这里不要把“实时推送”理解成“所有机器瞬间同时生效”。以 Nacos 为例，2.x 引入了 gRPC 长连接，配置变化可以通过长连接推给客户端，但真正生效仍然受客户端数量、网络、服务端负载、本地缓存刷新等因素影响。

所以降级开关设计时，要默认接受一个事实：**不同机器之间可能会有短暂不一致。**

### 用 Nacos 做降级开关时要注意什么？

如果项目里用的是 Nacos，有几个坑要提前知道。

第一，Nacos 2.x 和 1.x 的通信方式不完全一样。Nacos 2.x 新增了 gRPC 通信，所以除了主端口 8848，还会用到 9848、9849 这类端口。官方文档也明确提到，9848 是客户端 gRPC 请求服务端端口，9849 是服务端之间通信端口。

第二，升级时要注意兼容性。Nacos 2.0 服务端可以兼容 1.x 客户端，但 2.x 客户端不能连接 1.x 服务端，因为 2.x 客户端会使用 gRPC。

第三，如果中间有 Docker、防火墙、安全组、Nginx、VIP 之类的网络层，端口映射一定要提前处理。尤其是 9848 端口没放开时，客户端可能会出现连接不上、配置拉不到的问题。官方文档也提到，使用 VIP/Nginx 时需要配置 TCP 转发，不能按普通 HTTP 转发来处理。

第四，网络分区或客户端长连接异常时，客户端可能只能继续使用本地旧配置。所以预案里要写清楚：如果降级开关没有及时推到所有节点，系统应该怎么处理。

这也是为什么降级不能只依赖一个开关。关键链路最好还要配合超时、熔断、限流、缓存兜底一起做。

### 服务降级有哪些分类？

降级按照是否自动化可分为：

- **自动开关降级**（由规则引擎、熔断器、限流器或监控告警触发）
- **人工开关降级**（由值班人员或运营预案通过配置平台触发，如秒杀、电商大促等）

自动降级按触发条件分几种常见类型：

- **超时降级**：RT 持续超过阈值（阈值可以参考 P99/P999 监控基线，但具体框架触发是逐请求 RT + 窗口聚合，不是直接拿 P99 比较），触发后返回默认值。需要注意幂等性保护，否则重试风暴比原始故障更麻烦。
- **失败降级**：异常率超过阈值（比如 50%）时触发，返回兜底数据。兜底数据得提前预热到缓存里。
- **故障降级**：下游返回 HTTP 5xx、RPC 异常、DNS 解析失败等硬性错误时触发，返回缓存数据。缓存没命中就直接返回默认值，别再往下调了。
- **限流降级**：QPS 超过阈值时触发，返回排队页、无货提示或错误页。排队页需要防重入（幂等令牌），不然用户狂刷就失去意义了。

> 重试风暴：服务刚恢复，所有客户端同时重试，服务又被打挂。解决办法：带 Jitter 的指数退避、令牌桶限流、分组分批恢复。

## 大规模分布式系统如何降级？

在大规模分布式系统中，经常会有成百上千的服务。在大促前往往会根据业务的重要程度和业务间的关系批量降级。

### 降级平台能力

大型互联网公司通常会有统一的降级平台，需要具备这些能力：

- **分级管理**：服务按优先级分级（1-10 级或 L0-L4，看团队约定），核心业务必须经过评审，依赖关系要提前梳理清楚。
- **批量降级**：按级别或分组批量执行，编排好执行顺序、版本化推送、一键回滚。灰度、预览、审批走完再动手，别一把全关了才发现砍到核心链路。通常不要求严格 2PC 原子性。
- **动态开关**：配置中心（Nacos 2.x gRPC 或 Apollo）实时推送，不需要重启。
- **效果验证**：灰度 + 监控，指标对比确认降级生效且没误伤。
- **一键回滚**：配置版本化，变更审计，出问题了快速回退。

### 降级预案制定

1. **业务分级**：先分清哪些服务不能动（如下单、支付），哪些可以关（如推荐、评论），定义优先级
2. **依赖分析**：画出调用链，找出关键路径和单点依赖——哪个挂了会连累一片
3. **降级策略**：给每个非核心服务设计降级方案，别忘了失败路径怎么处理
4. **演练验证**：定期跑降级演练，纸上预案不跑一遍心里没底

> 网络分区时别纠结理论，想清楚这几件事就行：各服务在分区期间读本地缓存还是拒绝请求、跨区写入要不要停、核心链路怎么保、要不要切成只读模式。
>
> **详细介绍：** [CAP & BASE理论详解](https://javaguide.cn/分布式/协议/cap-and-base-theorem.html)。

## 什么是 Fallback？

Fallback 可以理解成：**兜底结果**。

正常情况下，请求会去调用真实的业务逻辑，比如查推荐、查商品详情、查用户信息。但如果这次调用失败了，或者被限流、熔断规则拦住了，系统不能直接把异常甩给用户，而是要返回一个提前准备好的结果。

比如推荐服务挂了，就先返回空列表；商品详情接口超时了，就返回缓存里的旧数据；活动页接口异常了，就切到静态页面。

这就是 Fallback 的作用：**别让一次失败，把整个链路都拖垮。**

不过要注意，Fallback 不是用来“修好问题”的，它只是让系统在异常情况下还能勉强可用。用户看到的内容可能不完整，也可能不是最新的，但至少页面不会直接炸掉。

### Sentinel 里的 blockHandler 和 fallback 有什么区别？

在 Sentinel 里，`blockHandler` 和 `fallback` 很容易被混在一起。它们都像是在“兜底”，但触发原因不一样。

简单说：

| **场景**                                                 | **走哪个方法** | **常见异常**   |
| -------------------------------------------------------- | -------------- | -------------- |
| 被 Sentinel 规则拦住，比如限流、熔断、系统保护           | blockHandler   | BlockException |
| 业务代码自己抛异常，比如空指针、远程调用失败、运行时异常 | fallback       | Throwable      |

举个例子。

接口被限流了，Sentinel 判断这个请求不能继续往下走，这时候进入 `blockHandler`。

如果请求已经进入业务方法了，但是业务里调用库存服务失败，抛了 `RuntimeException`，这时候才会进入 `fallback`。

如果 `blockHandler` 和 `fallback` 都配置了，Sentinel 规则触发的异常会优先进入 `blockHandler`；业务异常才进入 `fallback`。这一点别搞反，不然排查线上问题时会很绕。

![Sentinel：blockHandler 与 Fallback 的区别](https://oss.javaguide.cn/github/javaguide/高可用/fallback-and-circuit-breaker-blockHandler-vs-Fallback.png)

### 常见的 Fallback 做法

常见的 Fallback 做法有这么几种：

- **默认值返回**：直接返回一个静态默认对象。推荐列表为空就返回 `[]`，配置查不到就返回默认配置。注意默认值的结构要跟正常返回一致，别返回 null，不然上游拿到 null 直接 NPE。
- **缓存兜底**：读本地缓存或 Redis 里最近一次成功的结果。商品详情、用户信息这种读场景很适合。缓存可能过期，返回的时候最好标注一下数据时效；缓存穿透时别硬撑，兜底到默认值。
- **降级页面**：返回静态 HTML 或简化版页面，活动页、营销模块经常这么干。但静态资源本身也要有容灾——CDN 回源失败时的处理得提前想好。
- **写降级**：先写 Redis 或本地消息表，异步同步到 DB。秒杀扣减、积分发放等高并发写场景常用。代价是需保证最终一致性（对账/补偿），纯内存队列在节点宕机时会丢数据。

### Fallback 常见的坑

Fallback 本身也可能出问题，而且这种问题比正常故障更难发现。常见的坑有这几个：

- **Fallback 里面藏了远程调用**：兜底逻辑里调了 Redis、DB 或其他服务，结果这些依赖也挂了，雪崩反而加剧。优先用 Caffeine、本地 Map 或静态默认值；非得访问 Redis 的话，用独立连接池、独立超时和独立熔断器，缓存没命中就返回默认值，别再往下串了。
- **Fallback 返回 null**：上游拿到 null 直接 NPE，引发新的异常链。返回结构要跟正常返回一致，用空对象（Empty Object）而不是 null。
- **Fallback 逻辑太复杂**：兜底本身变慢，拖垮调用线程。Fallback 逻辑必须极简，禁止复杂业务处理。
- **多个 Fallback 共用同一个缓存**：缓存被打满，所有兜底同时失效。按业务维度隔离缓存，核心链路独立缓存实例。

说白了：Fallback 是最后一道防线，必须比正常调用更快更简单。如果兜底里面还藏着同步远程调用且没超时保护，那不是兜底，是埋雷。

## 什么是熔断？

熔断，名字听起来有点抽象，简单理解就是及时止损。它就是应对微服务雪崩效应的一种链路保护机制，类似电路中的保险丝。

在微服务里，一个服务经常要调用另一个服务。正常情况下，请求一路往下走：

```text
服务 A -> 服务 B -> 服务 C
```

如果服务 C 突然变慢，服务 B 调 C 的线程就会一直等。B 的线程被占满后，A 调 B 也开始超时。再往上，调用 A 的服务也会被拖住。

最后就会出现一种很典型的情况：**明明只是服务 C 出了问题，结果整条链路都被拖垮了。**

熔断器就是为了解决这个问题。

它的思路很简单：如果发现下游已经明显不正常，就先别继续打它了，直接返回兜底结果。等一段时间后，再放少量请求过去试探一下。如果下游恢复了，再慢慢恢复正常调用。

这有点像电路里的保险丝。电流异常时先断开，避免把后面的设备一起烧坏。

### 雪崩是怎么发生的？

很多线上雪崩不是一瞬间发生的，而是一层一层传开的。

比如还是这条链路：

```text
服务 A -> 服务 B -> 服务 C
```

一开始可能只是服务 C 响应变慢。比如原来 50ms 返回，现在要 3 秒。

接着，服务 B 调 C 的线程开始排队。线程池里的线程都在等 C 返回，新的请求进来只能继续排队。

再往后，服务 A 调 B 也开始超时。A 自己的线程也被占住，接口响应越来越慢。

如果这时候客户端、RPC 框架或者业务代码还在不停重试，请求量会被进一步放大。最后不是一个服务慢，而是一串服务都慢，整条链路都开始不可用。

这就是雪崩效应。

![雪崩效应传播](https://oss.javaguide.cn/github/javaguide/高可用/fallback-and-circuit-breaker-avalanche-effect-spread.png)

### 一个更接近真实情况的例子

假设有一个广告点击链路：

```text
广告点击服务 A -> 渠道过滤服务 B -> Redis
```

正常情况下，A 每分钟处理 3-4 万次点击。有一天流量突然涨到 8 万多。

问题一开始出在 B。B 需要从 Redis 里读一段过滤数据，但这个 value 太大，`get` 一次要 3 秒多。

于是 A 调 B 开始大量超时。

如果 Dubbo 这类 RPC 接口还配置了失败重试，比如一次初始调用后又重试 2 次，那原本 1 次调用就可能变成 3 次调用。这里要注意，具体会不会这样，取决于 Dubbo 版本、接口配置和调用类型。尤其是写接口，一般不建议默认重试，至少要非常谨慎。

重试一多，B 收到的请求更多，线程池更快被打满，然后开始拒绝请求。A 这边继续收到超时和异常，连接、文件句柄、线程资源也被消耗。

最后，原本只是 Redis 读取慢，结果一路拖垮了 A、B 和上游链路。

这类事故里，重试经常是“加速器”。没有限流和熔断时，它会把一个局部故障放大成全链路故障。

所以线上不是不能重试，而是重试必须有边界：要有超时时间、最大次数、退避策略，还要配合限流和熔断。

### 熔断器有哪几种状态？

熔断器包含三种状态：

| 状态                 | 说明                   | 行为                                   | 状态转换条件                                                                                                                |
| -------------------- | ---------------------- | -------------------------------------- | --------------------------------------------------------------------------------------------------------------------------- |
| **Closed（关闭）**   | 正常状态，允许请求通过 | 记录失败率/慢调用比例                  | 失败率/慢调用比例 > 阈值 → Open                                                                                             |
| **Open（打开）**     | 熔断触发，拒绝请求     | 快速返回 Fallback，不再调用下游        | 经过冷却时间（不同框架名称不同，如 Hystrix 的 sleepWindow、Resilience4j 的 waitDurationInOpenState，典型值 10s） → HalfOpen |
| **HalfOpen（半开）** | 探测服务是否恢复       | 放行少量探路请求（数量取决于框架实现） | 探测请求满足成功条件 → Closed；失败 → Open                                                                                  |

![熔断器状态机](https://oss.javaguide.cn/github/javaguide/高可用/fallback-and-circuit-breaker-fuse-state-machine.png)

### Half-Open 和 Warm Up 不是一回事

这两个概念很容易混。

Half-Open 解决的是：**下游到底恢复没有？**

Warm Up 解决的是：**恢复以后，流量要不要慢慢放？**

也就是说，Half-Open 更像“探测”，Warm Up 更像“预热放量”。

比如服务刚重启，缓存还没热，JIT 也没完全稳定，数据库连接池也刚开始建立。这时候即使探测成功，也不代表马上能扛住全部流量。

所以更稳的做法是：

1. Half-Open 先放少量请求探测；
2. 探测成功后，不要立刻打满流量；
3. 再用 Warm Up、限流或者分批放量，让服务慢慢恢复。

Sentinel 的 Warm Up 属于流控里的冷启动策略，默认 `coldFactor` 是 3，也就是一开始从 `threshold / 3` 左右的 QPS 慢慢升到配置阈值。

恢复期间不要只看平均耗时。平均值很容易掩盖少量极慢请求。更建议同时盯 P99、P999、线程池活跃数、数据库连接池活跃数和错误率。

### Sentinel 支持哪些熔断策略？

Sentinel 1.8.0 之后，熔断降级主要有三类策略：慢调用比例、异常比例、异常数。官方文档里的 DegradeRule 也说明了这些字段，比如 `count`、`timeWindow`、`minRequestAmount`、`statIntervalMs`、`slowRatioThreshold` 等。

**1. 慢调用比例**

这种策略看的是慢请求占比。

比如你设置最大 RT 是 500ms，那么超过 500ms 的请求就算慢调用。接着 Sentinel 会在一个统计窗口里计算慢调用比例。

如果窗口里的请求数达到最小请求数，并且慢调用比例超过阈值，就触发熔断。

这个策略适合处理“下游没报错，但越来越慢”的情况。

**2. 异常比例**

这种策略看的是失败请求占比。

比如最近一段时间里，请求数量达到最低要求，并且异常比例超过 50%，就触发熔断。

它适合那种下游开始大量报错的场景，比如 RPC 异常、运行时异常、服务端 5xx。

**3. 异常数**

这种策略看的是异常次数。

比如 1 分钟内异常数超过 50 次，就触发熔断。

它比异常比例更直观，但对流量大小比较敏感。高 QPS 接口和低 QPS 接口不能套同一套阈值。

### P99 能不能直接当熔断条件？

不建议这么理解。

P99 是监控指标，适合用来观察接口整体表现，也适合辅助你设置熔断阈值。

但 Sentinel 触发熔断时，不是简单拿 P99 跟阈值比较。它的逻辑更接近：

1. 先看单次请求是不是慢调用或异常；
2. 再放到统计窗口里计算比例或数量；
3. 请求数达到最小阈值后，再判断是否触发熔断。

所以 P99 更适合回答这个问题：**我的阈值设得合不合理？**

比如某接口平时 P99 是 120ms，你把慢调用阈值设成 100ms，那很可能误伤。

如果平时 P99 是 120ms，突然涨到 800ms，那就说明下游可能真的有问题，熔断阈值也需要结合这个基线来评估。

低 QPS 接口尤其要小心。如果窗口太短、最小请求数太小，一两个偶发慢请求就可能触发熔断。更稳的做法是适当拉长统计窗口，或者提高最小请求数。

## 降级和熔断有什么区别？

降级和熔断经常被放在一起说，但它们解决的问题不一样。

降级关注的是：系统出问题后，还能以什么方式继续服务用户。

比如推荐服务挂了，商品详情页别跟着白屏，可以先隐藏推荐区；活动接口超时了，可以先展示静态活动页；用户标签查不到，可以先按普通用户处理。

也就是说，降级更像是业务层面的取舍：哪些功能可以先牺牲，哪些核心链路必须保住。

熔断关注的是：下游已经不正常了，还要不要继续调用。

比如订单服务调用库存服务，库存服务已经大量超时。这时候如果还继续打请求，只会让库存服务更慢，也会把订单服务自己的线程池拖死。熔断器发现下游异常后，会先拦住请求，快速返回兜底结果，等一段时间后再放少量请求过去探测。

一句话记：**降级是"出了问题后怎么继续服务"，熔断是"异常依赖还要不要继续调"。**

### 限流、熔断、降级分别管什么？

这三个概念也很容易混。

**限流管入口。** 它解决的是"流量太多，要不要都放进来"。比如秒杀时 10 万个请求同时打进来，系统只能扛 1 万个，那就必须拦掉一部分。

**熔断管下游。** 它解决的是"下游已经慢了或挂了，要不要继续调"。如果继续调，下游恢复不了，自己也会被拖垮。

**降级管结果。** 它解决的是"请求被限流了、下游被熔断了、业务出异常了，接下来给用户返回什么"。可以返回默认值、缓存数据、静态页面，也可以关闭某个非核心功能。

更口语一点说：

- **限流**：别让太多请求进来
- **熔断**：别再打已经异常的下游
- **降级**：出问题后换一种方式继续服务
- **Fallback**：真正返回的兜底结果

Fallback 不是一个独立的治理策略，它更像是限流、熔断、降级触发后的"兜底动作"。

> 打个比方：把系统想象成一个商场。限流就是控制进商场的人数，人太多了先在门口排队；降级就是商场临时关闭餐饮区和电影院，但超市、药店这些核心区域继续营业；熔断就是发现某个供应商出问题了，先暂停向它下单，过一会儿再少量试几单看看恢复没有。

### 一次请求里它们怎么协同？

一条真实请求链路里，限流、熔断、降级通常是分层生效的。

1. **网关/入口限流**：请求刚进来时，先判断入口流量有没有超过系统承载能力。如果超过了，直接返回"系统繁忙，请稍后再试"，不要让流量继续往后打。
2. **服务内限流**：有些请求过了网关，但某个服务自己的线程池、连接池、数据库已经快扛不住了，这时服务内部也可以做限流，保护自己的关键资源。
3. **熔断器判断**：服务准备调用下游之前，先看这个下游是不是已经处于熔断状态。如果已经熔断，就不要继续调了，直接走兜底逻辑。
4. **业务执行与 Fallback**：下游调用失败、业务代码抛异常，或者规则拦截了请求，就返回提前准备好的兜底结果。比如空列表、缓存数据、默认对象、静态页面。

一句话总结：**限流拦入口，熔断断下游，降级保核心，Fallback 给兜底结果。**

![请求保护流程](https://oss.javaguide.cn/github/javaguide/高可用/fallback-and-circuit-breaker-request-protection-process.png)

### Sentinel 注解方式的最小示例

下面这个例子先看懂 `blockHandler` 和 `fallback` 的分工就行：

```java
@RestController
public class OrderController {

    @SentinelResource(
        value = "createOrder",
        blockHandler = "createOrderBlockHandler",
        fallback = "createOrderFallback",
        exceptionsToIgnore = {IllegalArgumentException.class}
    )
    @PostMapping("/order")
    public OrderVO createOrder(@RequestBody OrderDTO dto) {
        return orderService.create(dto);
    }

    // 限流、熔断、系统保护等 Sentinel 规则触发时，进入 blockHandler
    public OrderVO createOrderBlockHandler(OrderDTO dto, BlockException ex) {
        return OrderVO.degraded("当前下单人数过多，请稍后重试");
    }

    // 业务异常进入 fallback
    // 方法签名需要和原方法一致，或者额外多一个 Throwable 参数
    public OrderVO createOrderFallback(OrderDTO dto, Throwable t) {
        return OrderVO.failure("下单失败，请稍后再试");
    }
}
```

有几个点要讲清楚：

`blockHandler` 处理的是 Sentinel 拦截类异常，比如限流、熔断、系统保护触发后的 `BlockException`。`fallback` 处理的是业务代码里抛出来的异常，比如远程调用失败、运行时异常等。它的方法签名要和原方法一致，或者额外加一个 `Throwable` 参数。

如果 `blockHandler` 和 `fallback` 同时配置，Sentinel 规则触发的异常只会进入 `blockHandler`，不会进入 `fallback`。这个地方很容易写错。

另外，不是所有业务异常都应该 fallback。比如参数校验失败、权限不足、库存不足，这些本来就应该明确告诉上游，不应该被统一兜底成"系统繁忙"。这类异常可以用 `exceptionsToIgnore` 排除掉。

## 有哪些现成解决方案？

Spring Cloud 体系里，常见的熔断、限流、降级方案主要有这几个：

- **Hystrix 1.5.18**：老牌组件，很多早期 Spring Cloud Netflix 项目都用过。但它已经进入维护模式，不再主动迭代，新项目一般不建议再选。
- **Sentinel 1.8.x**：阿里开源的流量治理组件，国内 Spring Cloud Alibaba 项目里很常见。它不只是熔断，还包含限流、流量整形、热点参数限流、系统自适应保护等能力。
- **Resilience4j 2.x**：轻量级容错库，模块拆得比较细，包含熔断、限流、重试、舱壁隔离等能力。Spring Boot 3 / Java 17 项目里经常会考虑它。
- **Spring Retry**：主要解决重试问题，本身不是完整的熔断降级框架。一般会配合 Spring Cloud CircuitBreaker 或业务超时策略一起用。

版本号最好不要写死。Sentinel、Resilience4j 都还在更新，本文基于发文时可查的 Release，具体以各项目 GitHub Release 页面和版本矩阵为准。

### Hystrix、Sentinel、Resilience4j 怎么选？

不用一上来就背功能表，先按项目情况判断。

**老项目 Hystrix：能稳定跑就先别急着动，但要规划迁移。**

Hystrix 当年很火，线程池隔离、熔断、Fallback 都是它带起来的。但 Netflix 官方已经说明，Hystrix 现在处于维护模式，不再活跃开发。

如果是老项目已经用了 Hystrix，不需要为了"新"马上推倒重来。只要系统稳定，可以先继续用，同时把迁移排进后续 Spring Boot / Spring Cloud 升级计划里。但新项目就没必要再从 Hystrix 开始了，后面升级 Java、Spring Boot、Spring Cloud 时，兼容性成本会越来越高。

**Spring Cloud Alibaba / Dubbo 项目：优先看 Sentinel。**

Sentinel 的优势不是单纯"能熔断"，而是它围绕流量治理做得比较完整。它支持限流、熔断降级、热点参数限流、系统自适应保护，也有控制台可以看实时监控和配置规则。对 Spring Cloud Alibaba、Dubbo 这类项目来说，接入成本通常更低。

但也别把 Sentinel Dashboard 当成生产配置中心。Dashboard 更适合做规则管理和查看效果，生产环境通常还要接 Nacos、Apollo 等数据源做规则持久化，否则重启后规则可能丢。

**Spring Boot 3 / Java 17+ 新项目：可以优先看 Resilience4j。**

Resilience4j 的特点是轻量、模块化。你需要熔断，就引 CircuitBreaker；需要限流，就引 RateLimiter；需要重试，就引 Retry；需要隔离，就引 Bulkhead。

它和函数式编程、Reactor、Spring Boot 3 的组合会更自然一些。如果你的项目是 Spring Boot 3、Java 17+，又不依赖 Spring Cloud Alibaba 生态，Resilience4j 通常是更干净的选择。

### 简单对比

| 维度               | Sentinel                                    | Hystrix                  | Resilience4j                           |
| ------------------ | ------------------------------------------- | ------------------------ | -------------------------------------- |
| **维护状态**       | 活跃维护                                    | 维护模式                 | 活跃维护                               |
| **主要定位**       | 流量治理组件                                | 熔断降级组件             | 轻量级容错库                           |
| **熔断能力**       | 慢调用比例、异常比例、异常数                | 异常比例为主             | 异常比例、慢调用、异常数等             |
| **限流能力**       | 强，支持 QPS、并发线程、热点参数等          | 较弱                     | 有 RateLimiter 模块                    |
| **隔离能力**       | 并发线程数控制                              | 线程池隔离 / 信号量隔离  | SemaphoreBulkhead / ThreadPoolBulkhead |
| **流量整形**       | 支持 Warm Up、匀速排队                      | 不突出                   | 不突出                                 |
| **系统自适应保护** | 支持                                        | 不支持                   | 不支持                                 |
| **控制台**         | 有 Sentinel Dashboard                       | Hystrix Dashboard 已过时 | 通常自行接监控体系                     |
| **适合场景**       | Spring Cloud Alibaba、Dubbo、国内 Java 项目 | 存量老项目               | Spring Boot 3、Java 17+、轻量化项目    |

初学者只要记住三点：老项目 Hystrix 能稳定跑就先别急着动；Spring Cloud Alibaba / Dubbo 项目优先看 Sentinel；Spring Boot 3 / Java 17+ 新项目可以优先看 Resilience4j。

### 隔离策略怎么理解？

熔断只是"不继续调异常下游"，隔离解决的是"别让一个依赖把所有资源吃光"。

**线程池隔离**：给某个下游依赖单独分一个线程池。比如订单服务要调用库存服务，就让库存调用走自己的线程池。库存服务慢了，最多把这个线程池打满，不会把订单服务的主线程池一起拖死。优点是隔离更彻底，坏处是成本更高——线程多了以后会有上下文切换开销，线程池大小也不好估，P99 可能变差。Hystrix 默认就是线程池隔离。

**信号量隔离**：限制同时进来的请求数量。比如最多允许 100 个请求同时调用库存服务，超过就直接拒绝或降级。优点是轻量，不需要把业务调用切到另一个线程池里。缺点是如果下游调用本身一直阻塞，业务线程还是会被占住，所以通常要配合超时控制一起用。Sentinel 常见的并发线程数控制更接近信号量隔离的思路。

> 线程池隔离的代价不是很多人以为的"GC 扫描"，而是上下文切换。线程多了，CPU 在线程间频繁调度唤醒和挂起，sy 飙高，P99 尾延迟跟着恶化。到底严不严重，得看线程数、CPU sy/us 比例、队列等待时间和 P99 指标，别光凭感觉。

![隔离策略对比](https://oss.javaguide.cn/github/javaguide/高可用/fallback-and-circuit-breaker-isolation-strategy-comparison.png)

### Sentinel 的系统自适应保护是什么？

普通限流通常是手动设置一个阈值，比如 QPS 超过 1000 就限流。但真实系统不是这么简单，CPU、Load、RT、线程数、入口 QPS 都会影响系统是否已经接近极限。

Sentinel 的系统自适应保护就是想解决这个问题：不只看单个接口，而是从整个系统负载角度判断要不要拒绝部分请求。官方文档里说这个思路受 TCP BBR 启发，目标是在保证系统可靠的前提下维持较高吞吐。但别把它理解成完整的 TCP BBR——Sentinel 是借鉴思路，结合实时统计和规则阈值做保护，不是像 TCP 那样动态探测带宽、调整拥塞窗口。

可以粗略理解成：

**`当前并发请求数 > 系统最大 QPS × 最小 RT`**

如果当前在途请求已经超过系统估算的承载能力，就开始拒绝一部分流量。系统规则还可以按这些指标配置：

| 指标           | 说明                 | 常见用法                         |
| -------------- | -------------------- | -------------------------------- |
| **Load**       | Linux `load1` 值     | Load 明显高于 CPU 核数时触发保护 |
| **平均 RT**    | 入口流量平均响应时间 | 平均耗时持续升高时保护系统       |
| **并发线程数** | 当前处理中的请求数   | 防止线程资源被打满               |
| **入口 QPS**   | 入口流量大小         | 控制整体入口压力                 |

有个坑要注意：Sentinel 系统规则看的是平均 RT，不是 P99。平均值会掩盖长尾延迟，所以生产环境最好额外接 P99、P999、线程池、连接池、错误率这些监控。

### 选型建议

| 场景                            | 推荐方案                                   | 原因                                         |
| ------------------------------- | ------------------------------------------ | -------------------------------------------- |
| 存量 Hystrix 项目               | 先继续用，规划迁移                         | 不要为了替换而替换，优先保证稳定             |
| Spring Cloud Alibaba 项目       | Sentinel                                   | 生态适配好，控制台和规则模型更完整           |
| Dubbo 项目                      | Sentinel                                   | 接入和流量治理能力比较成熟                   |
| Spring Boot 3 / Java 17+ 新项目 | Resilience4j 或 Sentinel                   | Resilience4j 更轻量，Sentinel 治理能力更完整 |
| 只需要重试                      | Spring Retry / Resilience4j Retry          | 不要为了重试引完整治理框架                   |
| 需要系统级过载保护              | Sentinel，或网关 / Service Mesh / 自研平台 | Sentinel 三者里更完整，但不是唯一方案        |

如果团队已经在用 Nacos、Spring Cloud Alibaba，选 Sentinel 的成本会比较低。如果团队偏原生 Spring Boot 3、Micrometer、Prometheus 这套监控体系，Resilience4j 往往更自然。

### Hystrix 迁移到 Sentinel 要注意什么？

老项目从 Hystrix 迁到 Sentinel，不是简单把注解换一下。

**1. Fallback 要拆开。** Hystrix 里很多项目只有一个 `fallbackMethod`，限流、熔断、业务异常最后都走同一套兜底。Sentinel 里要分清：`blockHandler` 处理 Sentinel 规则拦截（限流、熔断、系统保护），`fallback` 处理业务代码抛出的异常。迁移时，原来的 fallback 逻辑最好拆一拆，不要混在一起。

**2. 隔离模型不一样。** Hystrix 默认线程池隔离，很多调用实际是在 Hystrix 线程池里跑的。Sentinel 更常见的是并发线程数控制，不会天然把下游调用切到独立线程池里。迁移后要重新检查超时、中断、线程池隔离这些能力，尤其是慢下游调用，如果没有单独超时控制，只靠 Sentinel 并发线程数限制不够。

**3. 规则配置方式不一样。** Hystrix 很多规则写在代码或配置文件里。Sentinel 更推荐把规则动态化，比如通过 Dashboard 管理，再接 Nacos、Apollo 等数据源做持久化和推送。生产环境不要只依赖 Dashboard 内存规则，否则服务重启、控制台重启后可能有规则丢失风险。

**4. 监控体系要重新接。** Hystrix 时代常见的是 Hystrix Dashboard + Turbine。迁到 Sentinel 后，可以先用 Sentinel Dashboard 看实时调用和规则效果，但生产上通常还要把指标接到 Prometheus、Grafana 或公司内部监控平台。如果用了集群限流，还要额外考虑 Token Server 的部署和可用性。

> 迁移最好跟着 Spring Boot / Spring Cloud 大版本升级一起做，单独迁移容易踩兼容性坑。如果存量系统到处都是 Hystrix 注解，可以先试 Sentinel 的 [Hystrix adapter](https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-hystrix) 过渡一下，但这个 adapter 本身的维护状态也要看一眼再决定。

### 小结

新项目一般不建议再选 Hystrix，它已经进入维护模式，更适合作为存量系统的过渡方案。如果项目在 Spring Cloud Alibaba、Nacos、Dubbo 这条技术线上，Sentinel 通常更顺手。如果是 Spring Boot 3 / Java 17+ 的新项目，团队又更偏 Micrometer、Prometheus、Reactor 这套生态，Resilience4j 会更轻量。

真正选型时别只看"谁功能多"，要看团队技术栈、Spring Cloud 版本、监控体系、规则是否要动态下发，以及后续谁来维护。


---

---

<!-- source: 服务限流详解-固定窗口、滑动窗口、令牌桶、漏桶与分布式限流.md -->

## [4] 服务限流详解：固定窗口、滑动窗口、令牌桶、漏桶与分布式限流

---
title: 服务限流详解：固定窗口、滑动窗口、令牌桶、漏桶与分布式限流
description: 服务限流原理与实现详解，系统讲解固定窗口、滑动窗口、令牌桶、漏桶等限流算法，以及 Guava RateLimiter、Bucket4j、Sentinel、Redis Lua、Redisson 的单机限流和分布式限流方案。
category: 高可用
icon: "mdi:speedometer-slow"
tag:
  - 服务限流
  - 高并发
head:
  - - meta
    - name: keywords
      content: 服务限流,限流算法,固定窗口,滑动窗口,令牌桶,漏桶,单机限流,分布式限流,Guava RateLimiter,Bucket4j,Sentinel,Redis Lua,Redisson 限流,限流面试题
---

针对软件系统来说，限流就是对请求的速率进行限制，避免瞬时的大量请求击垮软件系统。毕竟，软件系统的处理能力是有限的。如果请求量超过了系统的处理能力，软件系统可能直接就挂掉了。

限流可能会导致用户的请求无法被正确处理或者无法立即被处理，不过，这往往也是权衡了软件系统的稳定性之后得到的最优解。

现实生活中，处处都有限流的实际应用，就比如排队买票是为了避免大量用户涌入购票而导致售票员无法处理。

## 常见限流算法有哪些？

简单介绍 4 种非常好理解并且容易实现的限流算法！

> 图片来源于 InfoQ 的一篇文章[《分布式服务限流实战，已经为你排好坑了》](https://www.infoq.cn/article/Qg2tX8fyw5Vt-f3HH673)。

### 固定窗口计数器算法

固定窗口其实就是时间窗口，其原理是将时间划分为固定大小的窗口，在每个窗口内限制请求的数量或速率，即固定窗口计数器算法规定了系统单位时间处理的请求数量。

假如我们规定系统中某个接口 1 分钟只能被访问 33 次的话，使用固定窗口计数器算法的实现思路如下：

- 将时间划分固定大小窗口，这里是 1 分钟一个窗口。
- 给定一个变量 `counter` 来记录当前接口处理的请求数量，初始值为 0（代表接口当前 1 分钟内还未处理请求）。
- 1 分钟之内每处理一个请求之后就将 `counter+1` ，当 `counter=33` 之后（也就是说在这 1 分钟内接口已经被访问 33 次的话），后续的请求就会被全部拒绝。
- 等到 1 分钟结束后，将 `counter` 重置 0，重新开始计数。

![固定窗口计数器算法](https://static001.infoq.cn/resource/image/8d/15/8ded7a2b90e1482093f92fff555b3615.png)

优点：实现简单，易于理解。

缺点：

- 限流不够平滑。例如，我们限制某个接口每分钟只能访问 30 次，假设前 30 秒就有 30 个请求到达的话，那后续 30 秒将无法处理请求，这是不可取的，用户体验极差！
- 存在窗口边界突刺问题。例如，我们限制某个接口 1 分钟只能访问 1000 次，如果第 1 分钟最后 1 秒进入了 1000 个请求，第 2 分钟第 1 秒又进入了 1000 个请求，由于新窗口的计数器已重置，短短 2 秒内就可能放行 2000 个请求，等效 QPS 远超预期的 `1000/60≈16.7`。

### 滑动窗口计数器算法

**滑动窗口计数器算法** 算得上是固定窗口计数器算法的升级版，限流的粒度更小。

滑动窗口计数器算法相比于固定窗口计数器算法的优化在于：**它将一个固定窗口划分为多个更小的子窗口（格子）** 。

例如我们的接口限流每分钟处理 60 个请求，我们可以把 1 分钟分为 60 个窗口。每隔 1 秒移动一次，每个窗口一秒只能处理不大于 `60(请求数)/60（窗口数）` 的请求， 如果当前窗口的请求计数总和超过了限制的数量的话就不再处理其他请求。

很显然， **当滑动窗口的格子划分得越多，滑动窗口的滚动就越平滑，限流的统计就会越精确。**

![滑动窗口计数器算法](https://static001.infoq.cn/resource/image/ae/15/ae4d3cd14efb8dc7046d691c90264715.png)

优点：

- 相比于固定窗口算法，滑动窗口计数器算法能显著缓解窗口边界处的突发问题。
- 相比于固定窗口算法，滑动窗口计数器算法的粒度更小，可以提供更精确的限流控制。

缺点：

- 与固定窗口计数器算法类似，滑动窗口计数器算法依然存在限流不够平滑的问题。
- 相比较于固定窗口计数器算法，滑动窗口计数器算法实现和理解起来更复杂一些。

### 漏桶算法

我们可以把发请求的动作比作成注水到桶中，我们处理请求的过程可以比喻为漏桶漏水。我们往桶中以任意速率流入水，以一定速率流出水。当流入的水超过桶的容量时，多余的水会被丢弃，因为桶容量是不变的，保证了整体的速率。

如果想要实现这个算法的话也很简单，准备一个队列用来保存请求，然后我们定期从队列中拿请求来执行就好了（和消息队列削峰/限流的思想是一样的）。

![漏桶算法](https://static001.infoq.cn/resource/image/75/03/75938d1010138ce66e38c6ed0392f103.png)

优点：

- 实现简单，易于理解。
- 可以控制限流速率，避免网络拥塞和系统过载。

缺点：

- 无法应对突然激增的流量，因为只能以固定的速率处理请求，对系统资源利用不够友好。
- 桶流入水（发请求）的速率如果一直大于桶流出水（处理请求）的速率的话，那么桶会一直是满的，一部分新的请求会被丢弃，导致服务质量下降。

实际业务场景中，漏桶算法的适用范围相对窄一些。当业务需要允许一定程度的突发流量时，令牌桶通常更合适；但在需要严格控制输出速率的场景（如对接有明确 QPS 限制的第三方 API）中，漏桶仍然是合适的方案。

### 令牌桶算法

令牌桶算法也比较简单。和漏桶算法一样，我们的主角还是桶（这限流算法和桶过不去啊）。不过现在桶里装的是令牌了，请求在被处理之前需要从桶中获取一个令牌（获取即消费）。如果桶中没有令牌，请求就需要等待或被拒绝。我们根据限流大小，按照一定的速率往桶里添加令牌。如果桶装满了，就不能继续往里面继续添加令牌了。

![令牌桶算法](https://static001.infoq.cn/resource/image/ec/93/eca0e5eaa35dac938c673fecf2ec9a93.png)

优点：

- 可以限制平均速率，也允许在桶容量范围内处理短时突发流量。
- 可以动态调整生成令牌的速率。

缺点：

- 如果令牌产生速率和桶的容量设置不合理，可能会出现问题比如大量的请求被丢弃、系统过载。
- 相比于其他限流算法，实现和理解起来更复杂一些。

## 针对什么来进行限流？

实际项目中，还需要确定限流对象，也就是针对什么来进行限流。常见的限流对象如下：

- IP ：针对 IP 进行限流，适用面较广，简单粗暴。
- 业务 ID：挑选唯一的业务 ID 以实现更针对性地限流。例如，基于用户 ID 进行限流。
- 个性化：根据用户的属性或行为，进行不同的限流策略。例如， VIP 用户不限流，而普通用户限流。根据系统的运行指标（如 QPS、并发调用数、系统负载等），动态调整限流策略。例如，当系统负载较高的时候，控制每秒通过的请求减少。

针对 IP 进行限流是目前比较常用的一个方案。不过，实际应用中需要注意用户真实 IP 地址的正确获取。常用的真实 IP 获取方法有 X-Forwarded-For 和 TCP Options 字段承载真实源 IP 信息。虽然 X-Forwarded-For 字段可能会被伪造，但因为其实现简单方便，很多项目还是直接用的这种方法。

除了我上面介绍到的限流对象之外，还有一些其他较为复杂的限流对象策略，比如阿里的 Sentinel 还支持 [基于调用关系的限流](https://github.com/alibaba/Sentinel/wiki/流量控制#基于调用关系的流量控制)（包括基于调用方限流、基于调用链入口限流、关联流量限流等）以及更细维度的 [热点参数限流](https://github.com/alibaba/Sentinel/wiki/热点参数限流)（实时的统计热点参数并针对热点参数的资源调用进行流量控制）。

另外，一个项目可以根据具体的业务需求选择多种不同的限流对象搭配使用。

## 单机限流怎么做？

单机限流针对的是单体架构应用。

单机限流可以直接使用 Google Guava 自带的限流工具类 `RateLimiter` 。 `RateLimiter` 基于令牌桶算法，可以应对突发流量。

> Guava 地址：<https://github.com/google/guava>

除了最基本的令牌桶算法(平滑突发限流)实现之外，Guava 的`RateLimiter`还提供了 **平滑预热限流** 的算法实现。

平滑突发限流就是按照指定的速率放令牌到桶里，而平滑预热限流会有一段预热时间，预热时间之内，速率会逐渐提升到配置的速率。

下面通过两个简单的示例来了解。

我们直接在项目中引入 Guava 相关依赖即可使用。

```xml
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>31.0.1-jre</version>
</dependency>
```

> 本文示例基于 Guava 31.x，`RateLimiter` 的核心 API 在更高版本中仍保持兼容。

下面是一个简单的 Guava 平滑突发限流的 Demo。

```java
import com.google.common.util.concurrent.RateLimiter;

/**
 * 微信搜 JavaGuide 回复"面试突击"即可免费领取个人原创的 Java 面试手册
 *
 * @author Guide哥
 * @date 2021/10/08 19:12
 **/
public class RateLimiterDemo {

    public static void main(String[] args) {
        // 1s 放 5 个令牌到桶里也就是 0.2s 放 1个令牌到桶里
        RateLimiter rateLimiter = RateLimiter.create(5);
        for (int i = 0; i < 10; i++) {
            double sleepingTime = rateLimiter.acquire(1);
            System.out.printf("get 1 tokens: %ss%n", sleepingTime);
        }
    }
}

```

输出：

```bash
get 1 tokens: 0.0s
get 1 tokens: 0.188413s
get 1 tokens: 0.197811s
get 1 tokens: 0.198316s
get 1 tokens: 0.19864s
get 1 tokens: 0.199363s
get 1 tokens: 0.193997s
get 1 tokens: 0.199623s
get 1 tokens: 0.199357s
get 1 tokens: 0.195676s
```

需要注意的是，`acquire()` 是阻塞式获取令牌，在生产环境中通常更建议使用 `tryAcquire(timeout)` 设置等待上限，避免线程长时间阻塞。第一次输出等待时间为 `0.0s`，是因为 `RateLimiter.create(5)` 创建后桶里初始就有可用令牌。

下面是一个简单的 Guava 平滑预热限流的 Demo。

```java
import com.google.common.util.concurrent.RateLimiter;
import java.util.concurrent.TimeUnit;

/**
 * 微信搜 JavaGuide 回复"面试突击"即可免费领取个人原创的 Java 面试手册
 *
 * @author Guide哥
 * @date 2021/10/08 19:12
 **/
public class RateLimiterDemo {

    public static void main(String[] args) {
        // 1s 放 5 个令牌到桶里也就是 0.2s 放 1个令牌到桶里
        // 预热时间为3s,也就说刚开始的 3s 内发牌速率会逐渐提升到 0.2s 放 1 个令牌到桶里
        RateLimiter rateLimiter = RateLimiter.create(5, 3, TimeUnit.SECONDS);
        for (int i = 0; i < 20; i++) {
            double sleepingTime = rateLimiter.acquire(1);
            System.out.printf("get 1 tokens: %sds%n", sleepingTime);
        }
    }
}
```

输出：

```bash
get 1 tokens: 0.0s
get 1 tokens: 0.561919s
get 1 tokens: 0.516931s
get 1 tokens: 0.463798s
get 1 tokens: 0.41286s
get 1 tokens: 0.356172s
get 1 tokens: 0.300489s
get 1 tokens: 0.252545s
get 1 tokens: 0.203996s
get 1 tokens: 0.198359s
```

另外，**Bucket4j** 是一个非常不错的基于令牌/漏桶算法的限流库。

> Bucket4j 地址：<https://github.com/vladimir-bukhtoyarov/bucket4j>

相对于 Guava 的限流工具类来说，Bucket4j 提供的限流功能更加全面。不仅支持单机限流和分布式限流，还可以集成监控，搭配 Prometheus 和 Grafana 使用。

不过，毕竟 Guava 也只是一个功能全面的工具类库，其提供的开箱即用的限流功能在很多单机场景下还是比较实用的。

Spring Cloud Gateway 的内置限流器 `RedisRateLimiter` 基于 Redis + Lua 实现。Bucket4j 和 Resilience4j 更多是通过独立扩展或 Spring 生态组件与网关集成，并不是 Spring Cloud Gateway 内置限流器的替代演进关系。

Resilience4j 是一个轻量级的容错组件，其灵感来自于 Hystrix。自[Netflix 宣布不再积极开发 Hystrix](https://github.com/Netflix/Hystrix/commit/a7df971cbaddd8c5e976b3cc5f14013fe6ad00e6) 之后，Spring 官方和 Netflix 都更推荐使用 Resilience4j 来做限流熔断。

> Resilience4j 地址: <https://github.com/resilience4j/resilience4j>

一般情况下，为了保证系统的高可用，项目的限流和熔断都是要一起做的。

Resilience4j 不仅提供限流，还提供了熔断、负载保护、自动重试等保障系统高可用开箱即用的功能。并且，Resilience4j 的生态也更好，很多网关都使用 Resilience4j 来做限流熔断的。

因此，在绝大部分场景下 Resilience4j 或许会是更好的选择。如果是一些比较简单的限流场景的话，Guava 或者 Bucket4j 也是不错的选择。

## 分布式限流怎么做？

分布式限流针对的是分布式/微服务应用架构。在这种架构下，一种服务可能会被部署多份，如果需要控制全局配额，就要让多个实例共享限流状态。不过，并非所有微服务场景都必须使用分布式限流：如果配额可以按实例数均分（例如总配额 1000 QPS，10 个实例各限制 100 QPS），单机限流在性能和实现复杂度上反而更有优势。

分布式限流常见的方案：

- **借助中间件限流**：可以借助 Sentinel 或者使用 Redis 来自己实现对应的限流逻辑。
- **网关层限流**：比较常用的一种方案，直接在网关层把限流给安排上了。不过，网关层限流通常也需要借助中间件/框架。就比如 Spring Cloud Gateway 的分布式限流实现 `RedisRateLimiter` 就是基于 Redis+Lua 来实现的，再比如 Spring Cloud Gateway 还可以整合 Sentinel 来做限流。

如果你要基于 Redis 来手动实现限流逻辑的话，建议配合 Lua 脚本来做。

**为什么建议 Redis+Lua 的方式？** 主要有两点原因：

- **减少了网络开销**：我们可以利用 Lua 脚本来批量执行多条 Redis 命令，这些 Redis 命令会被提交到 Redis 服务器一次性执行完成，大幅减小了网络开销。
- **原子性**：一段 Lua 脚本可以视作一条命令执行，一段 Lua 脚本执行过程中不会有其他脚本或 Redis 命令同时执行，保证了操作不会被其他指令插入或打扰。

需要注意的是，Lua 脚本在 Redis 中会原子执行，也意味着脚本执行期间会阻塞 Redis 的其他操作。因此，限流脚本要尽量保持轻量，避免复杂计算或大范围遍历，并结合 Redis 的 `lua-time-limit` 配置防止脚本执行时间失控。

我这里就不放具体的限流脚本代码了，网上也有很多现成的优秀的限流脚本供你参考，就比如 Apache 网关项目 ShenYu 的 RateLimiter 限流插件就基于 Redis + Lua 实现了令牌桶算法/并发令牌桶算法、漏桶算法、滑动窗口算法。

> ShenYu 地址: <https://github.com/apache/incubator-shenyu>

![ShenYu 限流脚本](https://oss.javaguide.cn/github/javaguide/高可用/服务限流详解-固定窗口、滑动窗口、令牌桶、漏桶与分布式限流/shenyu-ratelimit-lua-scripts.png)

另外，如果不想自己写 Lua 脚本的话，也可以直接利用 Redisson 中的 `RRateLimiter` 来实现分布式限流，其底层实现就是基于 Lua 代码+令牌桶算法。

Redisson 是一个开源的 Java 语言 Redis 客户端，提供了很多开箱即用的功能，比如 Java 中常用的数据结构实现、分布式锁、延迟队列等等。并且，Redisson 还支持 Redis 单机、Redis Sentinel、Redis Cluster 等多种部署架构。

`RRateLimiter` 的使用方式非常简单。我们首先需要获取一个`RRateLimiter`对象，直接通过 Redisson 客户端获取即可。然后，设置限流规则就好。

```java
// 创建一个 Redisson 客户端实例
RedissonClient redissonClient = Redisson.create();
// 获取一个名为 "javaguide.limiter" 的限流器对象
RRateLimiter rateLimiter = redissonClient.getRateLimiter("javaguide.limiter");
// 尝试设置限流器的速率为每小时 100 次
// RateType 有两种，OVERALL 是全局限流，PER_CLIENT 是单 Client 限流（可以认为就是单机限流）
rateLimiter.trySetRate(RateType.OVERALL, 100, 1, RateIntervalUnit.HOURS);
```

接下来我们调用`acquire()`方法或`tryAcquire()`方法即可获取许可。

```java
// 获取一个许可，如果超过限流器的速率则会等待
// acquire()是同步方法，对应的异步方法：acquireAsync()
rateLimiter.acquire(1);
// 尝试在 5 秒内获取一个许可，如果成功则返回 true，否则返回 false
// tryAcquire()是同步方法，对应的异步方法：tryAcquireAsync()
boolean res = rateLimiter.tryAcquire(1, 5, TimeUnit.SECONDS);
```

`RRateLimiter` 的限流精度会受到 Redis 性能和网络延迟影响，在超高并发场景下可能出现轻微超限。Redis 故障或主从切换时，`tryAcquire()` 可能抛出异常，业务层需要提前确定降级策略：回退到本地限流、直接拒绝，还是短时间放行，取决于业务对稳定性和可用性的取舍。

## 总结

这篇文章主要介绍了常见的限流算法、限流对象的选择以及单机限流和分布式限流分别应该怎么做。

## 参考

- 服务治理之轻量级熔断框架 Resilience4j：<https://xie.infoq.cn/article/14786e571c1a4143ad1ef8f19>
- 超详细的 Guava RateLimiter 限流原理解析：<https://cloud.tencent.com/developer/article/1408819>
- 实战 Spring Cloud Gateway 之限流篇 👍：<https://www.aneasystone.com/archives/2020/08/spring-cloud-gateway-current-limiting.html>
- 详解 Redisson 分布式限流的实现原理：<https://juejin.cn/post/7199882882138898489>
- 一文详解 Java 限流接口实现 - 阿里云开发者：<https://mp.weixin.qq.com/s/A5VYjstIDeVvizNK2HkrTQ>
- 分布式限流方案的探索与实践 - 腾讯云开发者：<https://mp.weixin.qq.com/s/MJbEQROGlThrHSwCjYB_4Q>

<!-- @include: @article-footer.snippet.md -->


---

---

<!-- source: 高可用系统设计面试题总结-限流、熔断、重试、幂等、容灾与压测.md -->

## [5] 高可用系统设计面试题总结：限流、熔断、重试、幂等、容灾与压测

---
title: 高可用系统设计面试题总结：限流、熔断、重试、幂等、容灾与压测
description: 高可用系统设计面试复习路线，串联 SLA、单点故障、限流降级熔断、超时重试、接口幂等、冗余容灾、性能压测和故障演练等 Java 后端高频考点。
category: 高可用
tag:
  - 高可用
  - 面试题
  - 系统设计
head:
  - - meta
    - name: keywords
      content: 高可用面试题,高可用系统设计,高可用复习路线,系统设计面试题,SLA,限流面试题,熔断面试题,超时重试面试题,接口幂等面试题,冗余容灾,性能压测,故障演练
---

高可用系统面试考的不是“系统永远不出问题”，而是你是否理解：**故障一定会发生，关键是系统能不能限制故障范围、快速恢复，并避免把小故障放大成全站事故**。

这篇文章把 JavaGuide 现有高可用相关文章串成一条面试复习路线，适合准备后端开发、系统设计和中高级岗位面试。

## 高可用面试先建立故障视角

高可用设计可以从 5 个问题开始拆：

1. **请求太多怎么办？** 限流、排队、削峰。
2. **下游变慢怎么办？** 超时、重试、熔断、隔离。
3. **核心服务挂了怎么办？** 降级、冗余、故障转移。
4. **重复请求怎么办？** 幂等、防重、状态机。
5. **上线前怎么证明系统扛得住？** 压测、监控、演练、容量评估。

只要围绕这 5 个问题展开，高可用系统设计题就不会答散。

## 第一阶段：高可用系统设计总览

先建立整体框架，再看具体手段。

重点文章：

- [高可用系统设计指南](./高可用系统设计详解-SLA、限流熔断、降级容灾、缓存与灰度发布.md)
- [冗余设计详解](./冗余设计详解-RTORPO、高可用集群、同城灾备与异地多活.md)
- [性能测试详解](./性能测试和压力测试入门-RPS、QPS、TPS、P99 与压测工具.md)

高频面试问题：

- 什么是高可用？可用性 99.9%、99.99% 分别意味着什么？（99.9% 每月约 43 分钟不可用，99.99% 每月约 4 分钟不可用）
- 高可用和高性能有什么区别？
- 单点故障如何识别和消除？
- 冗余设计为什么不是简单多部署几台机器？
- 压测应该测什么？如何避免压测结果和线上表现差距过大？

这一阶段重点理解“系统会坏”这个前提。高可用设计的核心不是追求零故障，而是让故障可预期、可隔离、可恢复。

## 第二阶段：限流、降级和熔断

限流、降级、熔断经常一起被问，但它们解决的问题不一样。

重点文章：

- [限流算法详解](./服务限流详解-固定窗口、滑动窗口、令牌桶、漏桶与分布式限流.md)
- [服务降级和熔断详解](./服务降级与熔断详解-Fallback、熔断器状态机与 Sentinel Hystrix Resilience4j 选型.md)

高频面试问题：

- 固定窗口、滑动窗口、漏桶、令牌桶有什么区别？
- 为什么固定窗口限流可能出现临界突刺？比如每分钟限 100 次，在窗口末尾和下个窗口开头的 2 秒内可能放行 200 次。
- 令牌桶为什么更适合处理突发流量？
- 降级和熔断有什么区别？
- 熔断器通常有哪些状态？半开状态解决什么问题？
- 什么场景适合返回兜底数据？什么场景必须失败提示？

回答这类问题时，要说明触发条件和恢复机制。比如熔断不是“一失败就立刻切断”，而是需要错误率、慢调用比例、最小请求数、恢复探测等规则配合。不同实现（如 Sentinel、Resilience4j）的默认参数和窗口机制有差异，面试时最好能说出你用过的一种具体配置。

## 第三阶段：超时、重试和幂等

超时、重试、幂等是线上事故里非常常见的组合题。

重点文章：

- [超时和重试机制详解](./超时和重试机制详解-超时设置、指数退避、随机抖动、重试风暴与幂等.md)
- [接口幂等性详解](./接口幂等性设计详解-幂等键、Token、唯一索引、去重表与支付回调.md)

高频面试问题：

- 为什么所有远程调用都应该设置超时？
- 重试为什么可能放大故障？
- 哪些错误可以重试？哪些错误不应该重试？
- 指数退避和随机抖动解决什么问题？
- 什么是幂等？查询天然幂等吗？
- 支付、下单、发券这类接口如何设计幂等？常见方案包括唯一请求 ID + 去重表、数据库唯一约束、状态机控制、乐观锁等。

这部分最重要的结论是：**重试必须和超时、限流、幂等一起设计**。没有幂等的重试可能造成重复下单、重复扣款；没有退避的重试可能把下游彻底打挂。读操作重试相对安全，写操作重试必须配合幂等，重试次数通常建议控制在 3 次以内。

## 第四阶段：压测、监控和故障演练

很多同学准备高可用面试时只背方案，忽略验证视角。真实系统里，如果没有压测和监控，高可用设计就只是纸面设计。

重点文章：

- [性能测试详解](./性能测试和压力测试入门-RPS、QPS、TPS、P99 与压测工具.md)
- [高可用系统设计指南](./高可用系统设计详解-SLA、限流熔断、降级容灾、缓存与灰度发布.md)

高频面试问题：

- 压测指标应该关注哪些？QPS、RT、错误率和资源使用率各自的含义是什么？
- 如何做容量评估？
- 为什么要区分单接口压测和全链路压测？
- 线上监控应该覆盖哪些指标？
- 故障演练和混沌工程解决什么问题？

面试里可以这样收束答案：上线前通过压测确认容量边界，上线后通过监控发现异常，通过限流降级保护系统，通过预案和演练缩短恢复时间。

## 高可用系统设计题回答模板

遇到“如何设计一个高可用系统”这类题，可以按下面的顺序回答：

1. **明确业务场景和 SLA 目标**：不同业务、不同可用性等级决定了完全不同的复杂度和成本。
2. **识别核心链路**：哪些功能不能挂，哪些功能可以降级。
3. **消除单点故障**：服务、数据库、缓存、消息队列都要考虑冗余。
4. **控制入口流量**：限流、排队、削峰，避免系统被瞬时流量打穿。
5. **保护下游依赖**：超时、重试、熔断、隔离，防止故障扩散。
6. **保证请求安全**：幂等、防重、状态机，避免重复执行。
7. **建立观测和恢复能力**：监控、告警、压测、演练、预案。

这样答的好处是不会堆概念，而是沿着故障传播路径一步步收敛风险。

## 推荐复习顺序

临近面试可以按这个顺序复习：

1. 先看 [高可用系统设计指南](./高可用系统设计详解-SLA、限流熔断、降级容灾、缓存与灰度发布.md)，建立整体框架。
2. 再看 [限流算法详解](./服务限流详解-固定窗口、滑动窗口、令牌桶、漏桶与分布式限流.md)、[服务降级和熔断详解](./服务降级与熔断详解-Fallback、熔断器状态机与 Sentinel Hystrix Resilience4j 选型.md)。
3. 然后看 [超时和重试机制详解](./超时和重试机制详解-超时设置、指数退避、随机抖动、重试风暴与幂等.md)、[接口幂等性详解](./接口幂等性设计详解-幂等键、Token、唯一索引、去重表与支付回调.md)。
4. 最后补 [冗余设计详解](./冗余设计详解-RTORPO、高可用集群、同城灾备与异地多活.md)、[性能测试详解](./性能测试和压力测试入门-RPS、QPS、TPS、P99 与压测工具.md)。

高可用面试的核心不是把每个概念背得很长，而是能把它们串成一套故障治理体系：**出问题前能预防，出问题时能止损，出问题后能恢复和复盘**。


---

---

<!-- source: 高可用系统设计详解-SLA、限流熔断、降级容灾、缓存与灰度发布.md -->

## [6] 高可用系统设计详解：SLA、限流熔断、降级容灾、缓存与灰度发布

---
title: 高可用系统设计详解：SLA、限流熔断、降级容灾、缓存与灰度发布
description: 高可用系统设计指南，讲解 SLA 和多少个 9、单点故障治理、限流熔断、服务降级、缓存高可用、异步削峰、冗余容灾、灰度发布和故障恢复等核心方案。
category: 高可用
icon: "mdi:palette-swatch-outline"
tag:
  - 高可用
  - 系统设计
head:
  - - meta
    - name: keywords
      content: 高可用,高可用系统设计,高可用架构,SLA,多少个 9,单点故障,限流熔断,服务降级,缓存高可用,冗余容灾,灰度发布,故障恢复,系统稳定性
---

不管是平时刷的购物网站、用的在线支付，还是公司内部的核心业务系统，用户对"服务不可用"的容忍度越来越低。一次持续几分钟的故障，可能就会带来大量用户流失甚至直接的经济损失。

所以，如何让系统在各种异常情况下依然能提供稳定的服务，就成了后端开发和架构设计中绕不开的话题。这篇文章会把高可用系统设计的核心思路和常见方案梳理一遍，包括 SLA 指标、单点故障治理、限流熔断、服务降级、缓存高可用、异步削峰、冗余容灾、灰度发布和故障恢复等。

## 什么是高可用？可用性的判断标准是啥？

**高可用（High Availability，简称 HA）** 是指系统在绝大部分时间内能够持续提供正常服务的能力。高可用代表系统即使在发生硬件故障或者系统升级的时候，服务仍然是可用的。

一般情况下，我们使用 **多少个 9** 来评判一个系统的可用性，比如 99.9999% 就是代表该系统在所有的运行时间中只有 0.0001% 的时间是不可用的，这样的系统就是非常非常高可用的了！可用性较差的系统可能连 90%（1 个 9）都达不到。

| 可用性等级 | 可用性百分比 | 年度停机时间 | 典型场景     |
| ---------- | ------------ | ------------ | ------------ |
| 1 个 9     | 90%          | 36.5 天      | 个人博客     |
| 2 个 9     | 99%          | 3.65 天      | 普通企业系统 |
| 3 个 9     | 99.9%        | 8.76 小时    | 在线服务     |
| 4 个 9     | 99.99%       | 52.6 分钟    | 金融交易系统 |
| 5 个 9     | 99.999%      | 5.26 分钟    | 电信级系统   |

除此之外，系统的可用性还可以用 **某功能的失败次数与总的请求次数之比** 来衡量，比如对网站请求 1000 次，其中有 10 次请求失败，那么可用性就是 99%。

**SLA（Service Level Agreement，服务级别协议）** 是服务提供商与客户之间的正式承诺，通常会明确规定可用性目标。例如，云服务商承诺 99.95% 的 SLA，意味着每月最多允许约 22 分钟的停机时间。

## 哪些情况会导致系统不可用？

导致系统不可用的原因可以从 **内部因素** 和 **外部因素** 两个维度来分析：

**内部因素：**

1. **代码缺陷**：比如内存泄漏、死锁、循环依赖、空指针异常等代码质量问题，是导致线上故障的最常见原因之一。
2. **架构设计缺陷**：单点故障、缺少限流保护、服务间强耦合等架构问题，会在流量高峰时暴露出来。
3. **资源耗尽**：CPU、内存、磁盘、连接池等资源耗尽会直接导致服务不可用。
4. **配置错误**：错误的配置变更（如数据库连接串、超时时间配置不当）可能导致服务异常。

**外部因素：**

1. **硬件故障**：服务器宕机、磁盘损坏、网络设备故障等。
2. **流量激增**：突发的用户请求量（如秒杀活动）超过系统承载能力。
3. **网络攻击**：DDoS 攻击、CC 攻击等恶意攻击会耗尽系统资源。
4. **依赖服务故障**：数据库、缓存、消息队列、第三方 API 等依赖服务不可用。
5. **自然灾害**：机房停电、火灾、地震等不可抗力因素。

## 有哪些提高系统可用性的方法？

提高系统可用性的方法可以从 **预防**、**容错**、**恢复** 三个阶段来考虑：

![高可用系统韧性三阶段](https://oss.javaguide.cn/github/javaguide/高可用/ha-system-design-resilience-stages.png)

### 注重代码质量，测试严格把关

**代码质量是系统可用性的根基**。代码质量有问题比如比较常见的内存泄漏、循环依赖都是对系统可用性极大的损害。大家都喜欢谈限流、降级、熔断，但是从代码质量这个源头把关是首先要做好的一件很重要的事情。

如何提高代码质量？比较实际可用的就是 **Code Review**，不要在乎每天多花的那 1 个小时左右的时间，作用可大着呢！

另外，推荐几个对提高代码质量有实际效果的工具：

- [SonarQube](https://www.sonarqube.org/)：静态代码分析平台，可检测代码坏味道、安全漏洞和 Bug。
- Alibaba 开源的 Java 诊断工具 [Arthas](https://arthas.aliyun.com/doc/)：可在线排查 JVM 问题，支持热更新代码。
- [阿里巴巴 Java 代码规范](https://github.com/alibaba/p3c)（Alibaba Java Code Guidelines）：配套 IDEA 插件，实时检查代码规范。
- IDEA 自带的代码分析等工具。

### 使用集群，减少单点故障

**单点故障（Single Point of Failure，SPOF）** 是高可用的大敌。以 Redis 缓存为例：使用集群模式避免单点故障，是保障其高可用的关键手段。

当我们使用一个 Redis 实例作为缓存的时候，该 Redis 实例宕机后，整个缓存服务就可能不可用。使用集群之后，即使一台 Redis 实例宕机，也可以通过故障转移让其他实例接管。切换时间取决于部署模式和参数配置，Redis Sentinel/Cluster 通常需要数秒到数十秒，不应简单理解为“不到一秒”。

常见的集群模式：

- **主从复制（Master-Slave）**：一主多从，主节点负责写，从节点负责读，主节点故障时需要手动或借助哨兵进行故障转移。
- **哨兵模式（Sentinel）**：在主从复制基础上增加哨兵节点，实现自动故障检测和转移。
- **Redis Cluster 模式**：Redis 3.0+ 官方支持的数据分片方案，每个分片有主从副本，兼顾高可用和水平扩展。

### 限流

**限流（Rate Limiting）** 是保护系统的第一道防线。其原理是监控应用流量的 QPS 或并发线程数等指标，当达到指定的阈值时对流量进行控制，以避免被瞬时的流量高峰冲垮，从而保障应用的高可用性。——来自 [alibaba-Sentinel](https://github.com/alibaba/Sentinel "Sentinel") 的 wiki。

常见的限流算法包括：

- **固定窗口计数器**：实现简单，但存在临界点突刺问题。
- **滑动窗口计数器**：解决了固定窗口的临界问题，更加平滑。
- **漏桶算法**：以固定速率处理请求，适合流量整形。
- **令牌桶算法**：允许一定程度的突发流量，更加灵活。

### 超时和重试机制设置

一旦用户请求超过某个时间的得不到响应，就抛出异常。这个是非常重要的，很多线上系统故障都是因为 **没有进行超时设置或者超时设置的方式不对** 导致的。

我们在读取第三方服务的时候，尤其适合设置超时和重试机制。一般我们使用一些 RPC 框架的时候，这些框架都自带的超时重试的配置。如果不进行超时设置可能会导致请求响应速度慢，甚至导致请求堆积进而让系统无法再处理请求。

**重试的次数一般设为 3 次**，再多次的重试没有好处，反而会加重服务器压力（部分场景使用失败重试机制会不太适合）。同时，重试需要配合 **指数退避** 策略，避免重试风暴。

需要特别注意的是，重试的接口必须具备幂等性。对于创建订单、资金扣减这类非幂等写操作，应通过唯一请求 ID、业务唯一键、状态机等方式防止重复执行，而不是简单地把失败请求再发一遍。读操作可以相对积极地重试，写操作重试前最好先查询上一次请求是否已经生效。

### 熔断机制

超时和重试机制设置之外，**熔断机制** 也是很重要的。熔断机制说的是系统自动收集所依赖服务的资源使用情况和性能指标，当所依赖的服务恶化或者调用失败次数达到某个阈值时，熔断器进入 Open 状态，后续请求直接快速失败，不再调用下游服务，避免故障继续扩散。熔断通常会配合降级策略使用，比如返回兜底数据或调用备用服务。

熔断器有三种状态：

- **关闭（Closed）**：正常状态，请求正常通过。
- **打开（Open）**：熔断状态，请求直接失败，不调用下游服务。
- **半开（Half-Open）**：尝试恢复状态，放行少量请求探测下游服务是否恢复。

历史上广泛使用的流量控制和熔断降级框架有 Netflix Hystrix（已进入维护模式）和 Alibaba Sentinel。新项目通常更推荐使用 Sentinel 或 Resilience4j。

### 降级

**降级（Degradation）** 是在系统压力过大或部分服务不可用时，暂时关闭一些非核心功能，保证核心功能的可用性。

降级策略包括：

- **功能降级**：关闭推荐、评论等非核心功能。
- **数据降级**：返回缓存数据或默认数据，而非实时查询。
- **页面降级**：返回静态页面或简化版页面。

### 异步调用

异步调用是指调用方发起请求后不阻塞等待处理结果，而是立即返回，具体处理可以后续再做，秒杀场景用这个还是蛮多的。

但是，使用异步之后我们可能需要 **适当修改业务流程进行配合**，比如 **用户在提交订单之后，不能立即返回用户订单提交成功，需要在消息队列的订单消费者进程真正处理完该订单之后，甚至出库后，再通过电子邮件或短信通知用户订单成功**。

除了可以在程序中实现异步之外，我们常常还使用 **消息队列**，消息队列可以通过异步处理提高系统性能（削峰、减少响应所需时间）并且可以降低系统耦合性。

### 使用缓存

在高并发场景下，如果所有请求都直接打到数据库，数据库很可能因压力过大而崩溃。使用缓存缓存热点数据，因为缓存存储在内存中，所以速度相当地快！

缓存的典型应用场景：

- **热点数据缓存**：将访问频繁的数据放入 Redis 等缓存中。
- **页面缓存**：将渲染后的页面缓存起来，减少服务器压力。
- **本地缓存**：使用 Caffeine、Guava Cache 等本地缓存，减少网络开销。

缓存本身也要考虑高可用下的典型故障模式：

- **缓存穿透**：查询不存在的数据，请求全部穿透到数据库。常见应对方式有参数校验、空值缓存、布隆过滤器。
- **缓存击穿**：热点 Key 过期瞬间，大量请求同时打到数据库。常见应对方式有互斥锁、逻辑过期、热点 Key 永不过期 + 异步刷新。
- **缓存雪崩**：大量 Key 同时过期或缓存集群不可用。常见应对方式有过期时间加随机偏移、多级缓存、缓存集群高可用。

### 其他

- **核心应用和服务优先使用更好的硬件**：核心服务使用更高配置的服务器、SSD 硬盘等。
- **监控系统资源使用情况增加报警设置**：使用 Prometheus + Grafana 等监控方案，设置合理的告警阈值。
- **注意备份，必要时候回滚**：数据库定期备份，代码版本可追溯，支持快速回滚。
- **灰度发布**：将服务器集群分成若干部分，每天只发布一部分机器，观察运行稳定没有故障，第二天继续发布一部分机器，持续几天才把整个集群全部发布完毕，期间如果发现问题，只需要回滚已发布的一部分服务器即可。
- **定期检查/更换硬件**：如果不是购买的云服务的话，定期还是需要对硬件进行一波检查的，对于一些需要更换或者升级的硬件，要及时更换或者升级。

<!-- @include: @article-footer.snippet.md -->


---

---

<!-- source: 接口幂等性设计详解-幂等键、Token、唯一索引、去重表与支付回调.md -->

## [7] 接口幂等性设计详解：幂等键、Token、唯一索引、去重表与支付回调

---
title: 接口幂等性设计详解：幂等键、Token、唯一索引、去重表与支付回调
description: 接口幂等性设计详解，讲解幂等概念、幂等键、重复请求来源、Token 机制、唯一索引、去重表、乐观锁、悲观锁、分布式锁，以及订单和支付回调等场景的幂等方案。
category: 高可用
icon: mdi:shield-lock-outline
tag:
  - 接口幂等
  - 高并发
head:
  - - meta
    - name: keywords
      content: 接口幂等,幂等性设计,幂等键,Idempotency Key,Token 机制,唯一索引,去重表,分布式锁,乐观锁,支付回调幂等,订单幂等,重复提交,接口幂等面试题
---

接口幂等性是面试中常见的问题，也是日常开发过程中经常需要解决的问题。

## 什么是幂等（idempotency）？

幂等（idempotency）本身是一个数学概念，常见于抽象代数中，表示一个操作执行一次和执行多次产生的效果相同。放到函数上，可以理解为 $f(f(x)) = f(x)$。例如，$f(x)=|x|$ 就是幂等的，因为对一个数取一次绝对值和取多次绝对值，结果都一样。

在接口语义里，幂等主要指多次相同请求对服务端资源产生的预期效果，和执行一次请求一致。至于响应内容是否完全相同，要看业务设计；资金类接口通常会额外要求返回稳定的业务结果。

针对数据操作来说：

- 插入类操作要依赖业务唯一键或幂等键，避免重复创建数据。
- 更新类操作要区分赋值更新和累加更新。`update set status = 'PAID'` 这类赋值更新更容易做到幂等，`update set balance = balance - 100` 这类累加更新必须额外控制重复执行。

接口幂等性问题通常由网络波动、用户重复操作、客户端/网关超时重试、消息重复投递等触发；响应慢会放大这些重复请求的概率。

**不保证幂等会有什么后果？**

没有保证幂等会导致产生严重的生产级别的 Bug，比较典型的就是涉及到钱的业务场景。就比如在没有保证幂等性的情况下，我作为用户在付款的时候，同时点击了多次付款按钮，后端处理了多次相同的扣款请求，结果导致账户被扣了多次钱。这类问题在资金类业务中属于高风险生产事故。

所以，资金、库存、订单、优惠券这类场景都需要认真处理幂等。另外，保证幂等性并不是说前端做了就可以，后端同样也要做。

## 如何保证接口幂等性？

前端可以在用户提交请求后将按钮置灰，或者将按钮置为不可点击。这只能降低重复提交概率，不能作为幂等保证。用户可以刷新页面、重放请求、绕过前端，也可能由网关超时重试、消息队列重复投递触发重复调用。真正的幂等边界必须放在服务端，尤其是资金、库存、订单这类会改变业务状态的接口。

后端保证幂等性就稍微麻烦一点，方法也有很多种，比如悲观锁、唯一索引、去重表、乐观锁、分布式锁、Token 机制等。

悲观锁和分布式锁的核心思想都是通过加锁来保证同一时刻只有一个请求能被执行。但仅仅这样是不够的，还需要配合根据业务逻辑进行幂等性判断，例如，注册场景检测指定的电话/邮箱/用户名是否已经被注册、订单支付场景检测订单的状态。

实际项目里更常见的是组合方案：**业务唯一键 / 幂等号负责识别重复请求，数据库唯一索引或去重表负责兜底，状态机负责防止状态回退；分布式锁只在需要串行化同一业务资源操作时使用。**

常见场景可以先这样理解：

- **表单重复提交**：前端按钮置灰只能减少重复点击，服务端最好再配一次性 Token，保证同一张表单只能成功提交一次。
- **创建订单**：订单号、请求号这类业务唯一键一定要有，数据库再加唯一索引兜底。重复请求进来时，不是再创建一笔订单，而是返回已有订单结果。
- **支付回调**：第三方交易流水号要能唯一标识一笔回调，再配合订单状态机和去重表，避免同一笔支付被重复入账。
- **库存扣减**：重点是防止重复扣和超卖，可以结合状态校验、乐观锁、Redis Lua 或数据库事务来做。
- **消息消费**：消息可能重复投递，所以要用消息 ID 或业务流水号记录消费结果。已经消费过的消息，直接跳过或者返回成功。

方案选择时可以遵循几个优先级：

1. 能用业务唯一键解决的，优先用业务唯一键。
2. 能用数据库唯一索引兜底的，不要只依赖缓存。
3. 涉及状态流转的，用状态机防止重复执行和状态回退。
4. 需要保护同一业务资源的临界区时，再考虑分布式锁。
5. 高风险资金场景要多层兜底，不要押宝单一机制。

### 悲观锁

在 Java 中，可以使用 `ReentrantLock` 类、`synchronized` 关键字这类 JDK 自带的悲观锁来保证同一时刻只有一个线程能够进行修改。不过，JDK 自带的锁属于本地锁，分布式环境下无法使用。

![本地锁](https://oss.javaguide.cn/github/javaguide/分布式/分布式锁入门-为什么需要分布式锁、锁粒度、超时续约与应用场景/jvm-local-lock.png)

除了利用 JDK 提供的悲观锁之外，数据库自身也自带排他锁（X 锁）。排他锁又称写锁/独占锁，事务在修改记录的时候获取排他锁，不允许多个事务同时获取。如果一条记录已经被加了排他锁，其他事务不能再对这条记录加不兼容的锁。

在 MySQL 里使用排他锁：

```sql
SELECT ... FOR UPDATE
```

排他锁只能在支持事务的存储引擎（如 InnoDB）中使用，且只能在事务中使用。`SELECT ... FOR UPDATE` 最好命中合适索引，否则 InnoDB 可能扫描并锁住大量记录，甚至接近全表锁定效果，严重影响并发。在 MySQL 默认的 RR（REPEATABLE READ）隔离级别下，InnoDB 可能使用 Next-Key Lock（记录锁 + 间隙锁），更要通过 `EXPLAIN` 确认执行计划命中索引。

高并发的场景下，激烈的锁竞争会造成线程阻塞，大量阻塞线程会导致系统的上下文切换，增加系统的性能开销。并且，悲观锁还可能会存在死锁问题，影响代码的正常运行。使用悲观锁时，要保证加锁顺序一致、事务尽量短、查询命中索引，并结合 `EXPLAIN` 和死锁日志排查锁等待问题。

### 乐观锁

乐观锁一般会使用版本号机制或 CAS 算法实现。

拿版本号机制来说，通过在表中增加一个版本号字段，每次更新数据时，检查当前版本号是否和数据库中的一致。如果一致，则更新成功，并且版本号加一。如果不一致，则更新失败，表示数据已经被其他请求修改过。

```sql
-- 更新数据，修改 price 并将 version 加一，并且检查 version 是否为 1（假设 version 的初始值为 1）
update goods set price = price + 100, version = version + 1 where id = 1 and version = 1;
-- 由于 version 已经变为 2，因此，下面的 SQL 执行无效
update goods set price = price + 100, version = version + 1 where id = 1 and version = 1;
```

高并发的场景下，乐观锁通常不会像悲观锁那样长时间阻塞等待，能减少锁竞争带来的线程堆积，在性能上往往会更胜一筹。但数据库更新仍可能涉及行锁，复杂事务下不能说完全没有死锁风险。如果冲突频繁发生（写占比非常多的情况），会频繁失败和重试（悲观锁的开销是固定的），这样同样会非常影响性能，导致 CPU 飙升。不过，这种方法主要适用于更新数据的场景。

乐观锁更新失败后要提前设计处理策略：可以返回明确的冲突提示，由调用方决定是否重试；也可以在服务端有限重试 2～3 次；还可以查询当前状态并返回已有结果。资金类场景不建议盲目自动重试，应优先返回冲突或查询最终状态。

### 唯一索引

通过在表中加上唯一索引，保证数据的唯一性。如果有重复的数据插入，会抛出异常，程序可以捕获异常并处理。不过，这种方法只适用于插入数据的场景。

```sql
create table t_order(
    id int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT "主键",
    `code` varchar(200) not null COMMENT "流水号",
    `customer_id`  int unsigned COMMENT "会员id",
    `amount` decimal(10,2) unsigned not null COMMENT "总金额",
    -- 省略其他订单字段
    -- 省略其他索引
    -- 订单流水号唯一
    UNIQUE unq_code(`code`)
) COMMENT="订单表";
```

不要只依靠唯一索引完成全部幂等逻辑，但插入类场景建议把唯一索引作为数据库层兜底，避免并发下产生重复数据。

### 去重表

去重表本质上也是一种唯一索引方案。去重表是一张专门用于记录请求信息的表，其中某个字段需要建立唯一索引，用于标识请求的唯一性。当客户端发出请求时，服务端会将这次请求的一些信息（如订单号、交易流水号等）插入到去重表中，如果插入成功，说明这是第一次请求，可以执行后续的业务逻辑；如果插入失败，说明这是重复请求，可以直接返回或者忽略。

```sql
CREATE TABLE deduplication_table (
    id int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT "主键",
    processed_code varchar(200) not null COMMENT "已处理的订单流水号",
    -- 省略其他字段
    UNIQUE unq_processed_code(processed_code)
) COMMENT="去重表";
```

去重表的插入要和后续业务操作放在同一个数据库事务中。事务提交成功，才表示“去重记录存在 = 业务已经处理完成”；如果业务逻辑失败回滚，去重记录也要一起回滚，后续请求才能正常重入。否则可能出现“去重记录已写入，但业务实际没完成”的不一致状态。分库分表导致去重表和业务表不在同一物理库时，需要额外考虑 TCC / Saga 等分布式事务方案，或者改用其他能保证一致性的设计。

### 分布式锁

分布式系统下，不同的服务/客户端通常运行在独立的 JVM 进程上。如果需要跨 JVM 串行化同一业务资源的操作，就可以考虑使用**分布式锁**。

![分布式锁](https://oss.javaguide.cn/github/javaguide/分布式/分布式锁入门-为什么需要分布式锁、锁粒度、超时续约与应用场景/distributed-lock.png)

基于 MySQL 虽然也能实现分布式锁（如利用 `SELECT ... FOR UPDATE` 或唯一索引），但性能和可靠性通常不如专门的协调服务，生产中较少采用。

通常情况下，我们一般会选择基于 Redis 或者 ZooKeeper 实现分布式锁，Redis 用的要更多一点。

关系型数据库也可以参与分布式场景下的并发控制，比如唯一索引兜底、状态机校验、行锁串行化；但乐观锁和唯一索引通常不归类为分布式锁。

关于分布式锁的详细介绍以及如何基于 Redis 和 ZooKeeper 实现分布式锁，我写过专门的文章介绍，推荐看看：

- [分布式锁介绍](https://javaguide.cn/分布式/distributed-lock.html)
- [分布式锁常见实现方案总结](https://javaguide.cn/分布式/distributed-lock-implementations.html)

需要注意的是，这里的分布式锁是根据唯一标识（比如订单号）生成的。获取到锁只说明当前可以进入临界区，不代表历史上没有处理过。进入临界区后仍必须查询业务状态或幂等记录。例如支付接口要检查订单是否已支付、交易流水号是否已处理，再决定执行业务逻辑还是直接返回历史结果。

以下示例基于 Redisson 3.x，使用 `RLock` 实现幂等的伪代码如下：

```java
// 唯一标识
String uniqueId = "order123";

// 1. 根据唯一标识生成分布式锁对象
RLock lock = redisson.getLock("lock:" + uniqueId);
boolean locked = false;

try {
    // 2. 尝试获取锁，最多等待 3 秒，拿到锁后 30 秒自动释放
    locked = lock.tryLock(3, 30, TimeUnit.SECONDS);
    if (!locked) {
        // 获取锁失败：返回处理中、稍后重试，或查询历史处理结果
        return;
    }

    // 3. 进入临界区后，仍要做业务幂等判断
    // 例如：查询订单状态 / 幂等流水是否已存在
    // 未处理才执行业务逻辑，已处理则直接返回历史结果
    ...
} finally {
    // 4. 只有当前线程持有锁时才能释放
    if (locked && lock.isHeldByCurrentThread()) {
        lock.unlock();
    }
}
```

如果不显式指定 `leaseTime`，Redisson 会通过 Watchdog 给持有中的锁续期；如果指定了 `leaseTime`，锁会在租约时间后自动释放。上面的 30 秒只是示例值，实际使用时应根据业务最长执行时间选择，通常建议设置为预估耗时的 2～3 倍。

使用分布式锁还要额外关注这些问题：

- 锁粒度：按订单号、用户 ID、资源 ID 加锁，不要使用全局锁。
- 锁超时：业务执行时间超过 `leaseTime` 时，锁可能提前释放。
- 锁释放：必须校验当前线程 / 当前 owner，避免释放别人的锁。
- 拿锁失败：要决定返回“处理中”、提示稍后重试，还是查询历史处理结果。
- 业务兜底：进入锁后仍要查订单状态或幂等流水，不能只依赖锁。

### Token 机制

Token 机制的核心思想是为每一次操作生成一个唯一性的凭证 token。Token 应由服务端生成，保证随机性、不可预测和短有效期。如果服务端存储 token，可以用 Redis 记录并一次性消费；如果做无状态 token，才需要考虑签名、防篡改和过期时间。

这样的话，就需要两次请求才能完成一次业务操作：

1. 请求获取服务器端 token，token 需要设置有效时间（可以设置短一点），服务端将该 token 保存起来（通常保存在缓存中）。
2. 执行真正的请求，将上一步获取到的 token 放到 header 或者作为请求参数。服务端验证 token 的有效性，如果有效，执行业务逻辑；如果无效，拒绝请求，返回提示信息。

服务端验证 token 时，不能先 `GET` 再 `DEL`。Redis 6.2.0 及以上版本可以使用 `GETDEL`，低版本可以使用 Lua 脚本完成“校验 + 删除”的原子操作，确保同一个 token 只能被一个请求消费。

得物技术的[分布式系统设计中的并发访问解决方案](https://mp.weixin.qq.com/s/yvKASWcRLfOok-NFPrIRsw)这篇文章把这个过程图解得挺清晰。

![](https://oss.javaguide.cn/github/javaguide/分布式/idempotent-token.png)

先执行业务逻辑再删除 token 还是先删除 token 再执行业务逻辑呢？两者似乎都有风险：

- 先执行业务逻辑的话，客户端可能会在该 token 还存在的时候又携带 token 发起请求，由于 token 还存在，第二次请求也会验证通过。
- 先删除 token 的话，如果业务逻辑执行超时或者出现网络波动，客户端需要重试请求，那 token 就用不成了。

一般更推荐先原子消费 token，再执行业务逻辑；但要配套失败提示、重新获取 token、业务事务回滚和幂等流水记录。资金类场景不能只靠 token，还要用订单状态和交易流水兜底。

Token 机制依赖 Redis 保存 token 生命周期，也要提前设计 Redis 不可用时的降级策略。普通表单可以提示稍后重试；资金类接口不建议熔断放行，宁可返回失败，也要避免重复扣款或重复入账。

### 支付回调幂等流程

支付回调是幂等设计里非常典型的场景，第三方支付平台可能因为网络超时、响应丢失等原因多次回调同一笔交易。一个更稳妥的流程如下：

1. 回调请求携带第三方交易流水号 `transaction_id`。
2. 回调记录表对 `transaction_id` 建唯一索引。
3. 查询订单状态，只有 `UNPAID -> PAID` 这类合法状态流转才允许更新。
4. 更新订单状态、写资金流水、写回调记录放在同一个数据库事务中。
5. 重复回调直接返回成功，避免第三方继续重试。

## 如何验证幂等方案？

幂等方案不能只看代码，还要通过测试和数据校验确认它真的有效。尤其是订单、支付、库存这类场景，不能只测“正常请求成功一次”，还要故意制造重复请求、超时、失败和回滚。

比较实用的验证方式有这几类：

1. **并发压测**：同一个订单号、支付流水号或幂等 key，同时发起 50～100 个请求，最终只能有一次真正执行业务逻辑。其他请求要么返回相同结果，要么返回“处理中”或“已处理”，不能产生多条订单、多条资金流水或多次库存扣减。
2. **重试测试**：模拟客户端超时重试、网关重试、第三方回调重试、MQ 重复投递等情况。重点看重复请求进来后，是不是能命中幂等记录或业务状态，而不是重新执行业务逻辑。
3. **异常测试**：在业务执行到一半时制造异常，比如订单状态已更新但流水写入失败、Token 已消费但事务回滚、拿到分布式锁后服务重启。恢复后再次请求，数据仍然要能对齐，不能出现“半成功半失败”的脏状态。
4. **数据校验**：压测或异常测试结束后，对订单表、流水表、库存表、去重表做交叉校验。例如同一笔支付只能有一条成功流水，订单只能从 `UNPAID` 变成 `PAID` 一次，库存扣减数量要和成功业务单数一致。
5. **日志审计**：日志里要能查到幂等 key、请求 ID、业务单号、处理状态和返回结果。线上真出问题时，能根据这些字段判断请求是第一次处理、重复处理、处理中，还是被幂等逻辑拦截了。

简单来说，验证幂等不是看“接口会不会返回成功”，而是看重复请求和异常路径下，业务数据是否始终只被正确处理一次。

## 参考

- 高并发下如何保证接口的幂等性？：<https://mp.weixin.qq.com/s/7P2KbWjjX5YPZCInoox-xQ>
- 解决幂等问题，只需要记住这个口诀！：<https://mp.weixin.qq.com/s/EatpiCzNlTw1viO_flQIpg>


---

---

<!-- source: 冗余设计详解-RTORPO、高可用集群、同城灾备与异地多活.md -->

## [8] 冗余设计详解：RTO/RPO、高可用集群、同城灾备与异地多活

---
title: 冗余设计详解：RTO/RPO、高可用集群、同城灾备与异地多活
description: 冗余设计详解，讲解硬件冗余、服务冗余、数据冗余和地域冗余，覆盖 RTO/RPO、高可用集群、主备模式、主主模式、同城灾备、异地灾备、同城多活、异地多活和故障转移。
category: 高可用
icon: "mdi:server-network-outline"
tag:
  - 冗余设计
  - 容灾
head:
  - - meta
    - name: keywords
      content: 冗余设计,高可用集群,RTO,RPO,服务冗余,数据冗余,容灾架构,同城灾备,异地灾备,同城多活,异地多活,故障转移,主备模式,主主模式
---

不管是硬件故障、机房断电，还是某个服务突然挂掉，单点永远是系统里最脆弱的环节。想让系统在各种意外情况下还能扛得住，最基本也最有效的办法就是 **冗余**——关键资源多备几份，坏了一份还有其他的顶上。

这篇文章会把冗余设计的核心概念和常见方案梳理一遍：从 RTO/RPO 这两个容灾指标，到高可用集群、同城灾备、异地多活，再到 Redis Sentinel、Keepalived 这些具体的故障转移方案。

## 什么是冗余？

**冗余（Redundancy）** 是提升系统可用性和数据持久性的常见手段，其核心思想是 **通过部署多份相同的资源，当某一份资源出现故障时，其他资源可以接管其工作，从而保证系统的持续可用**。

冗余是提升系统可用性的基础手段，但冗余本身不等于高可用。只有配合故障检测、流量切换、数据复制、恢复演练和监控告警，才能真正降低故障影响。

冗余设计可以从以下几个维度来理解：

![冗余设计类型](https://oss.javaguide.cn/github/javaguide/高可用/redundancy-optimized-redundancy-types.png)

| 冗余类型     | 说明                   | 典型实现                                                     |
| ------------ | ---------------------- | ------------------------------------------------------------ |
| **硬件冗余** | 关键硬件设备部署多份   | 双电源、双网卡、RAID                                         |
| **软件冗余** | 应用服务部署多个实例   | 集群部署、容器化多副本                                       |
| **数据冗余** | 数据存储多份副本       | 数据库主从复制、分布式存储多副本                             |
| **网络冗余** | 网络链路和设备冗余     | 多运营商接入、双核心交换机、双链路、负载均衡主备或多实例部署 |
| **地域冗余** | 在不同地理位置部署系统 | 同城灾备、异地灾备、同城多活、异地多活                       |

**服务冗余**：同一个服务部署两个或多个实例，故障时自动切换到健康实例，大大减少系统的不可用时间，提高系统的可用性。

**数据冗余**：同一数据存储多份副本，任一副本丢失仍可从其他副本恢复，从而提升数据持久性与可用性。

实际上，日常生活中也有很多冗余设计的例子。拿我自己来说，我对于重要文件的保存方法就是冗余思想的应用。我日常所使用的重要文件都会同步一份在 GitHub 以及个人云盘上，这样就可以保证即使电脑硬盘损坏，我也可以通过 GitHub 或者个人云盘找回自己的重要文件。

## 容灾核心指标：RTO 和 RPO

在讨论容灾架构之前，需要先理解两个核心指标：

![RTO 与 RPO](https://oss.javaguide.cn/github/javaguide/高可用/redundancy-optimized-rto-rpo-timeline.png)

- **RPO（Recovery Point Objective，恢复点目标）**：系统在灾难发生后可接受的数据丢失窗口，也可以理解为恢复时数据最多允许回退到多久之前。RPO 越小，对同步复制、日志复制、跨站点一致性和写入延迟的要求越高。RPO = 0 通常意味着写入必须在多个故障域确认后才能返回，或者有等价的强一致提交机制；代价是写入延迟上升，并且在网络分区时需要在可用性和一致性之间做取舍。
- **RTO（Recovery Time Objective，恢复时间目标）**：可容忍的 **最大恢复时间**，即从故障发生到系统恢复正常服务的时间。RTO=0 表示目标上不允许可感知中断，但在真实系统中更常见的表述是接近 0 或用户无感切换，仍要看故障检测、流量切换和客户端重试行为。

> **RTO/RPO 是目标，不是结果**。它们是业务对容灾能力的约束，实际恢复能力取决于故障检测速度、切换自动化程度、数据复制延迟、人工流程和运维能力。声明了某个 RPO/RTO 不等于生产环境一定能做到，必须通过定期演练和压测来验证。另外，不同业务链路可以有不同的 RTO/RPO 要求，不必全站统一。

下面的 RPO/RTO 是典型配置下的 **量级参考**，实际结果取决于复制方式（同步/异步）、故障检测阈值、切换自动化程度和团队运维能力。多活是否能做到秒级 RTO/RPO，取决于流量调度、数据复制、故障检测、客户端重试、冲突解决和演练成熟度。

| 架构方案   | RPO            | RTO          | 成本 |
| ---------- | -------------- | ------------ | ---- |
| 单机无备份 | 可能全部丢失   | 不可预估     | 低   |
| 本地备份   | 取决于备份周期 | 小时级       | 低   |
| 同城灾备   | 秒级～分钟级   | 分钟～小时级 | 中   |
| 异地灾备   | 分钟～小时级   | 小时级       | 中高 |
| 同城多活   | 秒级           | 秒级         | 高   |
| 异地多活   | 秒级           | 秒级         | 很高 |

## 冗余架构方案对比

高可用集群（High Availability Cluster，简称 HA Cluster）、同城灾备、异地灾备、同城多活和异地多活是冗余思想在高可用系统设计中最典型的应用。

![容灾架构对比](https://oss.javaguide.cn/github/javaguide/高可用/redundancy-optimized-disaster-recovery-comparison.png)

### 高可用集群

**高可用集群** 是指同一个服务部署两个或多个实例，当正在使用的服务突然挂掉的话，可以切换到另外一台服务，从而保证服务的高可用。

高可用集群有两种常见模式：

![主备与主主模式](https://oss.javaguide.cn/github/javaguide/高可用/redundancy-optimized-ha-cluster-modes.png)

| 模式                           | 说明                       | 优点                     | 缺点                                                |
| ------------------------------ | -------------------------- | ------------------------ | --------------------------------------------------- |
| **主备模式（Active-Standby）** | 主节点提供服务，备节点待命 | 实现简单，单主写入易控制 | 资源利用率低，备节点闲置                            |
| **主主模式（Active-Active）**  | 多个节点同时提供服务       | 资源利用率高，无单点故障 | 写入冲突需要应用层解决；自增 ID、唯一约束等可能冲突 |

主备模式通常更容易控制写入路径；如果是同步复制，一致性更好但写延迟更高；如果是异步复制，切换时可能丢失尚未复制的数据。高可用集群单纯是服务的冗余，**并没有强调地域**。同城灾备、异地灾备、同城多活和异地多活实现了地域上的冗余。

### 同城灾备

**同城灾备** 不是简单地将服务冗余部署在同一个机房内，而是将主服务和备用服务分别部署在 **同一个城市的不同机房** 中。同城灾备通常指主备站点位于同一城市不同机房，常见形态是 active/passive：主站点处理生产流量，备站点平时不承载或只承载少量验证流量，故障时接管。具体是冷备、温备还是热备，要看成本和 RTO 要求。

这样可以避免单个机房出现停电、火灾等故障时导致服务完全不可用。

- **适用场景**：对 RTO 要求较高（分钟级），成本有限的企业。
- **典型配置**：同城双机房距离和延迟没有统一标准，通常需要通过专线时延、故障域隔离、供电和运营商路径独立性来评估。同步复制是否可接受，要以实际 RTT 和写入延迟预算为准。

### 异地灾备

**异地灾备** 类似于同城灾备，不同的是，相同服务部署在 **异地（通常距离较远，甚至是在不同的城市或者国家）的不同机房中**。

- **适用场景**：需要防范区域性灾难（地震、洪水）的核心业务系统。
- **挑战**：网络延迟较大，数据同步通常采用异步方式，可能存在数据丢失。

### 同城多活

**同城多活** 类似于同城灾备，但不再区分纯主备，多个同城机房都可以承载生产流量，这样可以充分利用系统资源，提高系统的并发。

- **适用场景**：对性能和可用性都有较高要求的系统。
- **技术要点**：需要解决数据同步、流量调度、会话管理等问题。

### 异地多活

**异地多活** 将服务部署在 **异地的不同机房** 中，并且，它们可以 **同时对外提供服务**。

和传统的灾备设计相比，同城多活和异地多活最明显的改变在于 **"多活"**，即所有站点都是同时在对外提供服务的。异地多活是为了应对突发状况，比如火灾、地震等自然或者人为灾害，以及区域性网络中断、机房级故障、合规要求等场景。

同城和异地的主要区别在于 **机房之间的距离**。异地通常距离较远，甚至是在不同的城市或者国家。

### 冷备 / 温备 / 热备 / 多活的层次

从容灾等级来看，从低到高可以形成如下连续光谱：

![容灾等级光谱](https://oss.javaguide.cn/github/javaguide/高可用/redundancy-optimized-dr-level-spectrum.png)

| 容灾等级 | 资源状态                       | 恢复速度 | 成本 | 典型场景                   |
| -------- | ------------------------------ | -------- | ---- | -------------------------- |
| **冷备** | 备用资源未运行，需手动启动     | 小时～天 | 低   | 非核心业务                 |
| **温备** | 部分资源常驻运行，需扩容接管   | 分钟级   | 中   | 一般业务容灾               |
| **热备** | 资源和数据持续同步，可快速切换 | 秒～分钟 | 高   | 核心业务                   |
| **多活** | 多站点同时承载生产流量         | 接近实时 | 很高 | 对可用性要求极高的核心业务 |

不同业务可以采用不同等级，不必全系统追求多活。关键在于根据业务影响面、故障概率和建设成本做取舍。

## 故障转移机制

光有冗余还不够，还需要配合 **故障转移（Failover）** 机制。所谓故障转移，简单来说就是 **将流量从故障节点快速切换到健康节点**。

故障转移可以是自动的，也可以是自动检测后人工确认。对无状态服务和缓存系统，通常追求自动切换；对数据库主切、跨地域切流、资金链路等高风险场景，很多团队会保留人工确认或审批步骤。

故障转移通常包含以下几个步骤：

![故障转移流程](https://oss.javaguide.cn/github/javaguide/高可用/redundancy-optimized-failover-process.png)

1. **故障检测**：通过心跳检测、健康检查等机制发现故障节点。检测阈值要权衡误判和漏判，太敏感容易误切，太保守会延长故障时间。
2. **故障确认**：避免误判，通常需要多次检测确认，并通过多数派投票、仲裁节点或租约机制防止脑裂。
3. **故障切换**：将流量切换到备用节点。
4. **故障通知**：发送告警通知运维人员。
5. **故障恢复**：故障节点恢复后重新加入集群。

对于有状态系统，还需要 **fencing 机制**，确保旧主在失联或恢复后不能继续对共享资源写入。否则即使新主切换成功，也可能出现双主写入和脑裂问题。常见手段包括 fencing token、STONITH（Shoot The Other Node In The Head）、写入令牌和租约。故障恢复后旧主不能直接重新加入写路径，需要先同步数据并通过仲裁确认。

![Fencing 防脑裂](https://oss.javaguide.cn/github/javaguide/高可用/redundancy-optimized-stateful-failover-fencing.png)

### Redis 哨兵模式示例

Redis Sentinel 可以监控 primary（旧文档中也常称 master）节点，在多数 Sentinel 判断 primary 故障后选举并提升某个 replica（旧文档中也常称 slave）为新的 primary；但它不保证 RPO=0。由于 Redis 复制通常是异步的，故障切换时可能丢失尚未复制到 replica 的数据。

生产常见部署至少 3 个 Sentinel。需要注意 quorum 只表示多少 Sentinel 同意 primary 客观下线；实际发起 failover 还涉及 Sentinel 多数派和 leader 选举，因此不要把 quorum 简单理解成 Sentinel 总数的一半。重点关注 `down-after-milliseconds`（实例不可达多久后被认为下线）、`failover-timeout`（failover 超时时间）等参数。

生产环境使用 Redis Sentinel 时，建议关注以下观测指标：

| 指标类别   | 具体指标                                           |
| ---------- | -------------------------------------------------- |
| 复制延迟   | replica 相对 primary 的 replication lag            |
| 故障检测   | `down-after-milliseconds` 触发次数                 |
| 切换耗时   | failover 从触发到完成的时间                        |
| 客户端感知 | 客户端重连耗时、主从切换期间写失败率               |
| 集群状态   | Sentinel quorum / majority 状态、Sentinel 节点存活 |

![Redis 哨兵模式](https://oss.javaguide.cn/github/javaguide/高可用/redundancy-optimized-redis-sentinel.png)

### Nginx + Keepalived 示例

Nginx 可以结合 Keepalived 来实现高可用。Keepalived 基于 VRRP 管理 VIP，可以让 VIP 在主备节点之间漂移，解决入口 IP 高可用问题。如果 Nginx 主服务器宕机的话，Keepalived 可以基于 VRRP 协议自动进行故障转移，备用 Nginx 服务器升级为主服务。由于使用的是 **虚拟 IP（VIP）**，对外 IP 不会改变。

需要注意的是：

- **Keepalived 不保证已有 TCP 连接无损迁移**，切换还受 ARP / 邻居表刷新、二层网络、云厂商 VIP 支持和健康检查脚本影响。
- 适合单机房或同二层网络下 VIP 漂移，不适合直接解决跨地域流量调度。
- 云环境下要确认是否支持自定义 VIP 和 ARP / 路由切换。
- 健康检查脚本要检查 Nginx 进程和业务端口，而不只是 Keepalived 进程本身。
- 生产中还要根据业务选择抢占或非抢占模式，避免主节点恢复后发生不必要的二次切换。

![Nginx 高可用架构](https://oss.javaguide.cn/github/javaguide/高可用/redundancy-optimized-nginx-keepalived.png)

## 异地多活的挑战

异地多活架构实施起来非常难，需要考虑的因素非常多：

![异地多活挑战](https://oss.javaguide.cn/github/javaguide/高可用/redundancy-optimized-geo-active-active-challenges.png)

| 挑战           | 说明                           | 解决思路                                                                                                        |
| -------------- | ------------------------------ | --------------------------------------------------------------------------------------------------------------- |
| **数据一致性** | 多个机房数据如何保持一致       | 单元化路由、最终一致性、TCC/Saga、冲突解决机制                                                                  |
| **网络延迟**   | 异地机房之间网络延迟较大       | 就近接入、数据分区                                                                                              |
| **流量调度**   | 如何将用户请求分配到合适的机房 | DNS 智能解析、GSLB                                                                                              |
| **会话管理**   | 用户会话如何在多机房之间共享   | 优先做无状态设计或按用户单元路由固定到同一站点；跨地域共享 session 虽然可行，但会引入延迟、一致性和故障隔离问题 |
| **成本**       | 多机房建设和运维成本高         | 按业务重要性分级部署                                                                                            |

异地多活的核心取舍可以用 CAP 来理解：跨地域网络延迟和分区不可避免，系统必须在强一致性和可用性之间取舍。但异地多活的工程难点不仅限于 CAP，还包括跨地域延迟、流量调度、数据分片、冲突解决、成本、合规和演练复杂度。常见做法是按用户或地域做单元化分片，让大部分读写落在同一机房；跨单元操作再通过 TCC / Saga、对账补偿或业务冲突解决保证最终一致。

**并不是所有业务都需要异地多活**。以下类型的业务要慎重评估：

- 强一致写入频繁且跨地域冲突多的业务
- 无法按用户 / 地域 / 租户切分的数据模型
- 对账补偿能力不足的资金链路
- 团队没有演练和运维能力支撑
- 建设成本高于故障损失预期的系统

通常要按业务影响面、故障概率、建设成本综合评估。

如果你想要深入学习异地多活相关的知识，推荐以下资料：

- [搞懂异地多活，看这篇就够了 - 水滴与银弹 - 2021](https://mp.weixin.qq.com/s/T6mMDdtTfBuIiEowCpqu6Q)
- [四步构建异地多活](https://mp.weixin.qq.com/s/hMD-IS__4JE5_nQhYPYSTg)
- [《从零开始学架构》— 28 | 业务高可用的保障：异地多活架构](http://gk.link/a/10pKZ)

<!-- @include: @article-footer.snippet.md -->


---

---

<!-- source: 性能测试和压力测试入门-RPS、QPS、TPS、P99 与压测工具.md -->

## [9] 性能测试和压力测试入门：RPS、QPS、TPS、P99 与压测工具

---
title: 性能测试和压力测试入门：RPS、QPS、TPS、P99 与压测工具
description: 性能测试入门指南，讲解 RPS、QPS、TPS、RT、P90/P99/P999、Little's Law、容量评估、曲棍球棒曲线、背压与自愈验证，以及负载测试、压力测试、稳定性测试和 JMeter、Gatling、k6、Locust、ab、wrk 等压测工具。
category: 高可用
icon: "mdi:speedometer"
tag:
  - 性能测试
  - 压力测试
head:
  - - meta
    - name: keywords
      content: 性能测试,压力测试,负载测试,稳定性测试,RPS,QPS,TPS,RT 响应时间,P99,容量评估,并发数,吞吐量,背压,利特尔法则,JMeter,Gatling,k6,Locust,ab 压测,wrk 压测,性能测试面试题
---

性能测试通常由专业的测试团队负责，那还需要我们开发学这个干嘛呢？了解性能测试的指标、分类以及工具等知识有助于我们更好地去写出性能更好的程序，另外作为开发这个角色，如果你会性能测试的话，相信也会为你的履历加分不少。

本文结合了笔者的实践经验以及向测试团队请教所得，除此之外，我还借鉴了一些优秀书籍，希望对你有帮助。

平时大家说“压测”，很多时候其实是在泛指性能测试相关工作：用工具模拟用户请求，观察系统在不同压力下的吞吐量、响应时间、错误率和资源使用情况。实际做压测时，先说清楚这次要验证什么。

## 不同角色看网站性能

### 用户

当用户打开一个网站的时候，最关注的是什么？当然是 **网站响应速度的快慢**。比如我们点击了淘宝的主页，淘宝需要多久将首页的内容呈现在我的面前，我点击了提交订单按钮需要多久返回结果等等。

所以，用户在体验我们系统的时候往往根据你的响应速度的快慢来评判你的网站的性能。

### 开发人员

用户与开发人员都关注速度，这个速度实际上就是我们的系统 **处理用户请求的速度**。

开发人员一般情况下很难直观的去评判自己网站的性能，我们往往会根据网站当前的架构以及基础设施情况给一个大概的值，比如：

1. 项目架构是分布式的吗？
2. 用到了缓存和消息队列没有？
3. 高并发的业务有没有特殊处理？
4. 数据库设计是否合理？
5. 系统用到的算法是否还需要优化？
6. 系统是否存在内存泄漏的问题？
7. 项目使用的 Redis 缓存多大？服务器性能如何？用的是机械硬盘还是固态硬盘？
8. ……

### 测试人员

测试人员一般会根据性能测试工具来测试，然后一般会做出一个表格。这个表格可能会涵盖下面这些重要的内容：

1. 响应时间；
2. 请求成功率；
3. 吞吐量；
4. ……

### 运维人员

运维人员会倾向于根据 **基础设施和资源的利用率** 来判断网站的性能，比如我们的服务器资源使用是否合理、数据库资源是否存在滥用的情况、当然，这是传统的运维人员，现在 Devops 火起来后，单纯干运维的很少了。我们这里暂且还保留有这个角色。

## 性能测试需要注意的点

几乎没有文章在讲性能测试的时候提到这个问题，大家都会讲如何去性能测试，有哪些性能测试指标这些东西。

### 明确压测目标

压测之前先想清楚目标，否则很容易变成“工具跑起来了，报告也生成了，但不知道结论是什么”。

常见目标有三类：

1. **上线前容量评估**：验证当前机器规格、实例数量、数据库配置和缓存策略是否能支撑预期流量。
2. **优化后效果验证**：确认慢 SQL、缓存、线程池、JVM 参数或架构调整之后，吞吐量、RT、错误率是否真的变好了。
3. **瓶颈定位**：通过逐步加压观察 CPU、内存、GC、数据库连接池、线程池、MQ 堆积等指标，找出最先扛不住的环节。

这三类目标对应的压测方法不一样。容量评估关注峰值水位和安全冗余，优化验证关注前后对比，瓶颈定位则需要更细的监控和链路追踪。

### 了解系统的业务场景

**性能测试之前更需要你了解当前的系统的业务场景。** 对系统业务了解得不够深刻，我们很容易犯测试方向偏执的错误，从而导致我们忽略了对系统某些更需要性能测试的地方进行测试。

比如我们的系统可以为用户提供发送邮件的功能，用户配置成功邮箱后只需输入相应的邮箱之后就能发送，系统每天大概能处理上万次发邮件的请求。很多人看到这个可能就直接开始使用相关工具测试邮箱发送接口，但是，发送邮件这个场景可能不是当前系统的性能瓶颈，这么多人用我们的系统发邮件，还可能有很多人一起发邮件，单单这个场景就这么人用，那用户管理可能才是性能瓶颈吧！

### 历史数据非常有用

当前系统所留下的历史数据非常重要，一般情况下，我们可以通过一些历史数据初步判定这个系统哪些接口调用的比较多、哪些服务承受的压力最大，这样的话，我们就可以针对这些地方进行更细致的性能测试与分析。

另外，这些地方也就像这个系统的一个短板一样，优化好了这些地方会为我们的系统带来质的提升。

### 请求模型要尽量贴近真实流量

单接口压测只能说明这个接口在当前条件下的表现，不能直接代表系统真实容量。真实用户访问系统时，通常会先登录、浏览、查询、下单、支付或提交表单，不同接口之间有顺序、比例和数据依赖。

因此，压测脚本最好按照真实业务链路来设计：高频接口多打一点，低频接口少打一点；读多写少的系统不要把写接口比例放得过高；需要鉴权、库存、订单状态流转的接口，也要提前准备合法的测试数据。否则，测出来的 QPS 很高，线上一到真实流量还是可能出问题。

### 先准备退出机制

压测尤其是线上压测，开始前必须准备好停止手段和保护阈值，例如最大 QPS、最大并发数、错误率阈值、P99 RT 阈值、CPU/内存阈值、数据库连接池阈值等。

一旦系统出现大量 5xx、RT 持续飙升、队列堆积不下降、数据库连接耗尽等情况，要能快速停止压测或自动熔断。压测的目的是发现问题，不是把线上服务打穿。

## 常见性能指标

做压测时，指标不能孤立看。RT、吞吐量和并发数放在一起，才能判断系统是在正常处理请求，还是已经开始排队。

![QPS、并发数与 RT 的关系](https://oss.javaguide.cn/github/javaguide/高可用/performance-test-metrics-relation.png)

### 响应时间

响应时间要先区分观测位置。对于后端接口压测，**响应时间 RT（Response Time）** 通常指压测客户端发出请求到收到响应的时间，包含网络传输、网关、服务端处理和响应返回。对于前端页面性能，用户体感还会受到 HTML 解析、JS 执行、资源加载、渲染和交互延迟影响，这类问题更适合用 Lighthouse、Chrome DevTools、WebPageTest 等工具分析。

平均 RT 只能看整体趋势。用户体感更容易被 P95、P99 这些长尾请求影响。接口压测和线上监控一般会同时看 **P50、P90、P95、P99**；核心链路在请求样本足够大时，再看 **P999**。

例如 P99 = 500ms，表示 99% 的请求能在 500ms 内返回。剩下 1% 的慢请求，可能来自 Cache Miss、慢 SQL 或 GC STW，它们会长时间占用连接和工作线程。并发高的时候，线程池被占满，新请求开始排队或被拒绝；上游再继续超时重试，流量还会被放大。大量超快响应会拉低平均值，长尾问题就被平均 RT 掩盖掉了。

下面只是一个低延迟在线接口的示例目标，不是所有系统通用标准：

| 分位值 | 示例目标 | 说明                     |
| ------ | -------- | ------------------------ |
| P90    | < 200ms  | 大多数用户的正常体验     |
| P99    | < 500ms  | 长尾体验与线程占用风险   |
| P999   | < 1s     | 高流量核心链路的极端长尾 |

阈值最好从业务 SLO、用户体验要求、上游超时时间、下游依赖能力和历史基线里推出来。另外，P999 对样本量比较敏感。如果一次测试只有几千个请求，P999 很容易被偶发抖动影响；如果接口本身 QPS 很低，P999 的统计意义也有限。这类接口可以先看 P99，或者拉长压测时间收集更多样本。

> **失败模式**：当下游偶发抖动导致 P999 飙升时，如果上游没有合理超时、限流和熔断，请求会长时间占用连接、线程或协程。进一步叠加重试后，可能出现线程池耗尽、连接池耗尽、队列堆积、错误率上升，严重时才可能触发 OOM。

### 并发数

**并发数指系统在同一时刻正在处理的请求数量**。

并发数反映了系统的 **负载能力**。需要注意区分以下概念：

- **并发用户数**：同时在线的用户数量。
- **并发请求数**：同一时刻系统正在处理的请求数量。
- **最大并发数**：系统能够承受的最大并发请求数，超过此值系统可能出现性能下降或崩溃。

### RPS、QPS 和 TPS

- **RPS（Requests Per Second）**：服务器每秒处理的 HTTP/RPC 请求数，更适合接口压测。
- **QPS（Queries Per Second）**：服务器每秒处理的查询次数，常用于数据库查询、搜索查询，也常被宽泛地当作请求吞吐量。
- **TPS（Transactions Per Second）**：服务器每秒完成的业务事务数，例如一次下单、一次支付、一次注册。

> QPS vs TPS：TPS 更偏业务语义。比如一次下单可以算 1 个 TPS，但它背后可能包含查询库存、创建订单、扣减库存、调用支付 4 次 HTTP/RPC 请求，对后端服务来说可能就是 4 RPS，还可能产生更多次数据库 QPS。

### 吞吐量

**吞吐量** 指系统单位时间内处理的请求数量。RPS、QPS、TPS 都是常用量化指标。

**Little's Law（利特尔法则）**：在系统未饱和的稳态下，`平均在途请求数 ≈ 吞吐量 × 平均响应时间`。这里的并发数指系统中正在处理或排队的平均请求数，不是在线用户数；RT 使用平均响应时间，不是 P99；吞吐量使用完成请求的平均速率。

例如平均 QPS 为 500，平均 RT 为 200ms（0.2s），系统内平均在途请求数约为 `500 × 0.2 = 100`。

这个公式只能用在线性响应区间。并发继续上去后，CPU 调度、锁争用（Lock Contention）和排队时间会一起放大，RT 往往非线性上升，吞吐量到达拐点后进入平台期甚至下降。图里的“曲棍球棒曲线”（Hockey Stick Curve）就是在说明这个现象：拐点之后 QPS 不升反降，系统已经进入非线性区。

![QPS 与并发数的曲棍球棒曲线](https://oss.javaguide.cn/github/javaguide/高可用/performance-test-hockey-stick-curve.png)

所以，生产容量不能只靠公式推算，还要通过全链路压测验证真实极限。

## 系统活跃度指标

### PV（Page View）

**访问量**，即页面浏览量或点击量，衡量网站用户访问的网页数量；在一定统计周期内用户每打开或刷新一个页面就记录 1 次，多次打开或刷新同一页面则浏览量累计。PV 从网页打开的数量/刷新的次数的角度来统计的。

### UV（Unique Visitor）

**独立访客**，统计 1 天内访问某站点的用户数。1 天内相同访客多次访问网站，只计算为 1 个独立访客。UV 是从用户个体的角度来统计的。

### DAU（Daily Active User）

**日活跃用户数量**，指一天内登录或使用产品的用户数（去重）。

### MAU（Monthly Active Users）

**月活跃用户人数**，指一个月内登录或使用产品的用户数（去重）。

### 实战计算示例

> **生产级容量评估**：只用 DAU 乘固定系数估峰值，很容易低估活动流量。整点秒杀、大促开抢这类场景，峰值通常和日均流量不是一个量级。可以先用历史日均请求量估算日均 QPS，再结合业务峰值倍数（如日均的 3～10 倍，视业务而定）得到初步峰值 QPS，最后根据 Little's Law 反推目标并发数并加上 1.5～2 倍安全冗余。这个结果只能作为压测目标的起点，最终还要通过 **全链路压测**（结合真实流量录制与回放，如 [GoReplay](https://goreplay.org/)）摸底真实吞吐量，而不是停在纸面估算。

## 性能测试分类

| 测试类型                         | 目的                         | 常见做法                                 |
| -------------------------------- | ---------------------------- | ---------------------------------------- |
| **基准测试（Benchmark）**        | 建立性能基线，方便前后对比   | 固定环境、固定脚本、固定数据             |
| **负载测试（Load Test）**        | 验证预期负载下是否达标       | 按预估流量模型逐步加压到目标水位         |
| **容量测试（Capacity Test）**    | 找到当前系统可承载上限       | 逐步加压，观察吞吐拐点和资源瓶颈         |
| **压力测试（Stress Test）**      | 观察超限后的退化、保护和恢复 | 超过预期负载，验证限流、熔断、自愈       |
| **稳定性测试（Soak/Endurance）** | 验证长时间运行稳定性         | 以接近真实负载持续运行较长时间           |
| **峰值测试（Spike Test）**       | 验证突增流量承受能力         | 短时间快速升压，再快速回落，观察恢复情况 |

![性能测试分类：压力水位怎么区分](https://oss.javaguide.cn/github/javaguide/高可用/performance-test-type-boundaries.webp)

这几类测试主要差在加压加到哪里：负载测试看目标流量能不能扛住；容量测试继续往上压，找拐点；压力测试越过预期负载，看系统怎么失败、怎么恢复。

### 基准测试

基准测试强调环境、脚本、数据和参数固定，方便比较优化前后的变化。比如同一接口在同一台机器上，改索引前后分别跑一轮，看平均 RT、P99、吞吐量和 CPU 水位是否变化。

### 负载测试

负载测试是在预期流量模型下验证系统是否达标。比如按照线上历史比例组合登录、查询、下单、支付等请求，逐步加压到目标 QPS，看响应时间、错误率和资源使用是否满足要求。

### 容量测试

容量测试会继续加大请求压力，直到服务器的某个资源达到饱和，或者系统响应时间、错误率已经不满足要求。它更关注当前架构和资源配置下的承载上限。

### 压力测试

压力测试会故意把流量推过设计水位。这个阶段可以接受快速失败，比如返回 429 或 503；不能接受请求一直挂着，连接不释放、线程池排队、队列越积越多，上游还在继续重试。测试时要看令牌桶、信号量、队列长度限制、熔断降级这些保护措施有没有真的生效；流量撤掉后，连接、线程、队列和吞吐量能不能回到正常水平。

### 稳定性测试

稳定性测试主要看长时间趋势。系统刚启动时一切正常，跑几个小时后才暴露的问题，通常就藏在这里。可以用接近线上比例的流量跑几个小时、一天或更久，重点盯趋势：堆内存是否只涨不回落、Full GC 是否变密、连接池是否长期打满、线程数是否持续增长、MQ 或本地队列是否越积越多、错误率是否一点点抬头。7×24 小时只是高要求场景里的常见做法，不是固定答案。

### 峰值测试

峰值测试适合模拟活动开场、整点秒杀、消息推送这类突然涌进来的流量。压测时先把流量在很短时间内拉高，再降回正常水位，看限流、排队、降级有没有按预期触发，以及流量回落后 RT、错误率、线程池和队列能不能降下来。

## 全链路压测

单接口压测只能告诉你某个接口在当前脚本下能跑到多少吞吐。复杂系统出问题时，瓶颈经常不在入口接口本身：网关鉴权没问题，库存服务开始排队；订单接口还能返回，MQ 已经堆积；应用 CPU 不高，数据库连接池先被打满。一次下单可能经过网关、鉴权、商品、库存、订单、支付、消息队列、缓存和数据库，任何一个环节先到瓶颈，最终都会反映到用户请求上。

![全链路压测：先把护栏搭好](https://oss.javaguide.cn/github/javaguide/高可用/full-link-performance-test-guardrails.webp)

做全链路压测时，流量从系统入口进来，沿着真实业务链路往后走，每个服务、组件和基础设施都会被带上压力。这种方式比单接口压测更接近线上流量，也更容易误伤真实数据和服务，所以先把几件事准备好：

1. **压测数据隔离**：使用压测账号、压测标识、影子表或影子库，避免污染真实订单、支付、库存等核心数据。
2. **压测流量识别**：让网关、服务、日志、监控、链路追踪都能识别压测流量，便于统计和快速止损。
3. **链路监控完整**：同时观察应用指标、机器指标、数据库指标、缓存指标、MQ 堆积、慢 SQL、GC 和线程池状态。
4. **熔断和限流可用**：压测前确认限流、降级、熔断、队列长度限制等保护机制已经生效。
5. **压测结果可复盘**：记录每一轮压测的并发数、QPS、P90/P99、错误率、资源水位和瓶颈点，方便和优化后的结果对比。

如果业务还没到需要线上全链路压测平台的阶段，先用 JMeter、Gatling、wrk 等工具把核心链路脚本跑清楚，能定位瓶颈、能保护数据、能快速停止，就已经能覆盖大部分容量评估和瓶颈定位场景。等业务复杂到需要频繁线上压测，再考虑专门的平台化建设。

## 常用性能测试工具

### 后端常用

既然系统设计涉及到系统性能方面的问题，那在面试的时候，面试官就很可能会问：**你是如何进行性能测试的？**

推荐几个比较常用的性能测试工具：

| 工具           | 语言/脚本                                   | 特点                                                 | 适用场景                         |
| -------------- | ------------------------------------------- | ---------------------------------------------------- | -------------------------------- |
| **JMeter**     | Java，GUI + CLI                             | 功能全面，GUI 适合编写和调试脚本，正式压测建议用 CLI | 企业复杂场景、接口链路压测       |
| **Gatling**    | Java、JavaScript、TypeScript、Scala、Kotlin | 代码驱动，报告和 CI 集成友好                         | 开发团队维护压测脚本、CI/CD 集成 |
| **k6**         | JavaScript 脚本，Go 引擎                    | 指标、阈值和 CI 集成友好                             | API 压测、SLO 回归               |
| **Locust**     | Python                                      | Python 编写用户行为，支持分布式扩展                  | Python 团队、复杂用户行为建模    |
| **wrk**        | C，支持 Lua 脚本                            | 轻量高性能                                           | HTTP 接口高并发基准测试          |
| **ab**         | C                                           | 简单轻量，Apache 自带                                | 快速冒烟或粗略基准测试           |
| **LoadRunner** | 商业套件                                    | 协议支持和管理能力强                                 | 企业级大规模测试                 |

没记错的话，除了 **LoadRunner**，上面几款都有开源或免费版本。

**选型建议：**

- **快速验证**：使用 `ab` 或 `wrk` 进行简单的接口压测。
- **复杂场景**：使用 `JMeter`，支持录制脚本、参数化、断言等功能。
- **代码驱动**：使用 `Gatling` 或 `k6`，适合开发人员维护脚本并接入 CI。
- **复杂用户行为建模**：使用 `Locust`，适合用 Python 描述用户行为。

### 前端常用

| 工具                            | 主要用途                                                 |
| ------------------------------- | -------------------------------------------------------- |
| **Chrome DevTools Performance** | 录制并分析页面运行时性能、长任务、JS 执行和渲染瓶颈      |
| **Lighthouse**                  | 自动审计页面性能、可访问性、最佳实践、SEO 等，并生成报告 |
| **WebPageTest**                 | 从真实浏览器、不同网络或地域视角测试页面加载体验         |
| **Fiddler/Charles**             | 抓包、改包、调试 HTTP 请求                               |

## 常见的性能优化策略

优化前先把请求链路跑清楚：入口网关、应用线程池、缓存、数据库、MQ、外部接口，哪个地方先排队，就先看哪里。

下面是一些性能优化时，我经常拿来自问的一些问题：

| 优化方向   | 检查项                                                   |
| ---------- | -------------------------------------------------------- |
| **缓存**   | 系统是否需要缓存？热点数据是否已缓存？                   |
| **架构**   | 系统架构本身是不是就有问题？是否需要读写分离、分库分表？ |
| **并发**   | 系统是否存在死锁的地方？锁的粒度是否合理？               |
| **内存**   | 系统是否存在内存泄漏？GC 是否频繁？                      |
| **数据库** | 数据库索引使用是否合理？是否存在慢 SQL？                 |
| **算法**   | 核心算法的时间复杂度是否可以优化？                       |
| **IO**     | 是否存在不必要的网络调用？是否可以批量操作？             |

<!-- @include: @article-footer.snippet.md -->

